package netif

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

// NetplanConfigPath qosnat 专用 netplan 片段（勿与 cloud-init 文件混编）
const NetplanConfigPath = "/etc/netplan/99-qosnat2.yaml"

var netplanManagedDown []string

// ApplyNetplan 根据 state 渲染并 netplan apply。applied 为 true 表示执行了 generate/apply。
func ApplyNetplan(net store.NetworkState) (applied bool, err error) {
	if _, err := exec.LookPath("netplan"); err != nil {
		return false, fmt.Errorf("netplan not installed (apt install netplan.io)")
	}
	body, down, err := RenderNetplan(net)
	if err != nil {
		return false, err
	}
	netplanManagedDown = down
	if len(body) == 0 {
		_ = os.Remove(NetplanConfigPath)
		// 无托管接口/VLAN/tunnel 时不要 netplan apply，避免启动时打乱系统路由。
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(NetplanConfigPath), 0755); err != nil {
		return false, err
	}
	if err := os.WriteFile(NetplanConfigPath, body, 0644); err != nil {
		return false, err
	}
	if out, err := exec.Command("netplan", "generate").CombinedOutput(); err != nil {
		return false, fmt.Errorf("netplan generate: %s %w", strings.TrimSpace(string(out)), err)
	}
	if out, err := exec.Command("netplan", "apply").CombinedOutput(); err != nil {
		return false, fmt.Errorf("netplan apply: %s %w", strings.TrimSpace(string(out)), err)
	}
	for _, dev := range netplanManagedDown {
		_, _ = exec.Command("ip", "link", "set", dev, "down").CombinedOutput()
	}
	return true, nil
}

// RenderNetplan 生成 YAML；无托管项时返回空 body
func RenderNetplan(net store.NetworkState) (body []byte, linkDown []string, err error) {
	ifaces := net.Ifaces
	vlans := net.VLANs
	tunnels := net.VXLANTunnels
	if ifaces == nil {
		ifaces = []store.IfaceConfig{}
	}
	if vlans == nil {
		vlans = []store.VLANIface{}
	}
	if tunnels == nil {
		tunnels = []store.VXLANTunnel{}
	}
	if len(ifaces) == 0 && len(vlans) == 0 && len(tunnels) == 0 {
		return nil, nil, nil
	}
	var b strings.Builder
	b.WriteString("# Generated by qosnat2 — do not edit manually\n")
	b.WriteString("network:\n")
	b.WriteString("  version: 2\n")

	if len(ifaces) > 0 {
		b.WriteString("  ethernets:\n")
		for _, ic := range ifaces {
			dev := strings.TrimSpace(ic.Device)
			if dev == "" || isNetplanExcluded(dev) {
				continue
			}
			if !ic.Up {
				linkDown = append(linkDown, dev)
			}
			b.WriteString(fmt.Sprintf("    %s:\n", dev))
			b.WriteString("      optional: true\n")
			if ic.DHCP4 {
				b.WriteString("      dhcp4: true\n")
			} else {
				b.WriteString("      dhcp4: no\n")
				addrs, aerr := normalizeNetplanAddrs(ic.IPv4)
				if aerr != nil {
					return nil, nil, aerr
				}
				if len(addrs) > 0 {
					b.WriteString("      addresses:\n")
					for _, a := range addrs {
						b.WriteString(fmt.Sprintf("        - %s\n", a))
					}
				}
			}
		}
	}

	if len(vlans) > 0 {
		b.WriteString("  vlans:\n")
		for _, v := range vlans {
			if v.Parent == "" || v.VID < 1 || v.VID > 4094 {
				continue
			}
			name := strings.TrimSpace(v.Name)
			if name == "" {
				name = VLANName(v.Parent, v.VID)
			}
			if !v.Up {
				linkDown = append(linkDown, name)
			}
			b.WriteString(fmt.Sprintf("    %s:\n", name))
			b.WriteString("      optional: true\n")
			b.WriteString(fmt.Sprintf("      id: %d\n", v.VID))
			b.WriteString(fmt.Sprintf("      link: %s\n", v.Parent))
			b.WriteString("      dhcp4: no\n")
			addrs, aerr := normalizeNetplanAddrs(v.IPv4)
			if aerr != nil {
				return nil, nil, aerr
			}
			if len(addrs) > 0 {
				b.WriteString("      addresses:\n")
				for _, a := range addrs {
					b.WriteString(fmt.Sprintf("        - %s\n", a))
				}
			}
		}
	}

	if len(tunnels) > 0 {
		b.WriteString("  tunnels:\n")
		for _, t := range tunnels {
			if t.VNI < 1 {
				continue
			}
			name := strings.TrimSpace(t.Name)
			if name == "" {
				name = store.VXLANIfaceName(t.VNI)
			}
			if !t.Up {
				linkDown = append(linkDown, name)
			}
			b.WriteString(fmt.Sprintf("    %s:\n", name))
			b.WriteString("      mode: vxlan\n")
			b.WriteString(fmt.Sprintf("      id: %d\n", t.VNI))
			b.WriteString(fmt.Sprintf("      local: %s\n", strings.TrimSpace(t.Local)))
			b.WriteString(fmt.Sprintf("      remote: %s\n", strings.TrimSpace(t.Remote)))
			port := t.Port
			if port <= 0 {
				port = 4789
			}
			b.WriteString(fmt.Sprintf("      port: %d\n", port))
			if u := strings.TrimSpace(t.Underlay); u != "" {
				b.WriteString(fmt.Sprintf("      link: %s\n", u))
			}
			b.WriteString("      dhcp4: no\n")
			addrs, aerr := normalizeNetplanAddrs(t.IPv4)
			if aerr != nil {
				return nil, nil, aerr
			}
			if len(addrs) > 0 {
				b.WriteString("      addresses:\n")
				for _, a := range addrs {
					b.WriteString(fmt.Sprintf("        - %s\n", a))
				}
			}
		}
	}

	return []byte(b.String()), linkDown, nil
}

// NetplanConfigPathForAPI 返回配置路径（供 API 展示）
func NetplanConfigPathForAPI() string { return NetplanConfigPath }

func normalizeNetplanAddrs(ipv4 []string) ([]string, error) {
	var out []string
	for _, cidr := range ipv4 {
		cidr = strings.TrimSpace(cidr)
		if cidr == "" {
			continue
		}
		if _, _, err := net.ParseCIDR(cidr); err != nil {
			if ip := net.ParseIP(cidr); ip == nil || ip.To4() == nil {
				return nil, fmt.Errorf("invalid ipv4 cidr: %q", cidr)
			}
			cidr += "/32"
		}
		out = append(out, cidr)
	}
	return out, nil
}

func isNetplanExcluded(dev string) bool {
	switch dev {
	case "lo":
		return true
	}
	if strings.HasPrefix(dev, "ifb") || strings.HasPrefix(dev, "veth") ||
		strings.HasPrefix(dev, "docker") || strings.HasPrefix(dev, "br-") {
		return true
	}
	return false
}

// IsNetplanManagedDevice 是否禁止直接 ip 配置（应走 netplan）
func IsNetplanManagedDevice(dev string) bool {
	return !isNetplanExcluded(strings.TrimSpace(dev))
}
