package dnsmasq

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	confPath  = "/etc/dnsmasq.d/qosnat2.conf"
	leasePath = "/var/lib/misc/dnsmasq.leases"
)

// Status 运行状态
type Status struct {
	Installed bool   `json:"installed"`
	Active    bool   `json:"active"`
	Config    string `json:"config_path"`
	LeasesRaw string `json:"leases_raw,omitempty"`
}

// Iface 网卡摘要
type Iface struct {
	Name  string   `json:"name"`
	Up    bool     `json:"up"`
	Addrs []string `json:"addrs,omitempty"`
}

func installed() bool {
	_, err := exec.LookPath("dnsmasq")
	return err == nil
}

// ListInterfaces 列出宿主机网卡（供绑定选择）
func ListInterfaces() ([]Iface, error) {
	out, err := exec.Command("ip", "-json", "addr", "show").Output()
	if err != nil {
		return nil, fmt.Errorf("ip addr: %w", err)
	}
	var raw []struct {
		Ifname    string `json:"ifname"`
		OperState string `json:"operstate"`
		AddrInfo  []struct {
			Family    string `json:"family"`
			Local     string `json:"local"`
			Prefixlen int    `json:"prefixlen"`
		} `json:"addr_info"`
	}
	if err := json.Unmarshal(out, &raw); err != nil {
		return nil, err
	}
	var list []Iface
	for _, l := range raw {
		if l.Ifname == "lo" {
			continue
		}
		iface := Iface{Name: l.Ifname, Up: l.OperState == "UP" || l.OperState == "UNKNOWN"}
		for _, a := range l.AddrInfo {
			if a.Family != "inet" {
				continue
			}
			iface.Addrs = append(iface.Addrs, fmt.Sprintf("%s/%d", a.Local, a.Prefixlen))
		}
		list = append(list, iface)
	}
	return list, nil
}

// ApplyOpts dnsmasq 运行期选项（含 NAT64/DNS64）
type ApplyOpts struct {
	ExceptWAN string
	DevLAN    string
	Nat       store.NatState
	LANIPv4   string // 网关 LAN IPv4，DHCP 关闭时 dnsmasq 监听
	LANIPv6   string // 网关 LAN IPv6，local_unbound 时下发给客户端
}

// RenderConf 生成 dnsmasq 片段
func RenderConf(dhcp store.DHCPState, opts ApplyOpts) string {
	var b bytes.Buffer
	b.WriteString("# Generated by qosnat2 — do not edit manually\n")
	if !dhcp.ServiceActive() && !opts.Nat.DNS64UsesDnsmasqRelay() {
		b.WriteString("# dnsmasq service disabled\n")
		return b.String()
	}
	if dhcp.ServiceActive() {
		writeBindSection(&b, dhcp, opts)
	}
	if dhcp.Enabled {
		writeDHCPSection(&b, dhcp)
	}
	if dhcp.DNSEnabled {
		b.WriteString("port=53\n")
		writeUpstreamDNSSection(&b, dhcp, opts)
	} else if dhcp.Enabled {
		b.WriteString("port=0\n")
	}
	writeDNS64Section(&b, dhcp, opts)
	return b.String()
}

func writeBindSection(b *bytes.Buffer, dhcp store.DHCPState, opts ApplyOpts) {
	iface := strings.TrimSpace(dhcp.Interface)
	if iface == "" {
		iface = strings.TrimSpace(opts.DevLAN)
	}
	if iface == "" {
		return
	}
	exceptWAN := strings.TrimSpace(opts.ExceptWAN)
	b.WriteString(fmt.Sprintf("interface=%s\n", iface))
	b.WriteString("bind-interfaces\n")
	if wan := exceptWAN; wan != "" && wan != iface {
		b.WriteString(fmt.Sprintf("except-interface=%s\n", wan))
	}
}

func writeDHCPSection(b *bytes.Buffer, dhcp store.DHCPState) {
	if dhcp.Authoritative {
		b.WriteString("dhcp-authoritative\n")
	}
	lease := formatLeaseTime(dhcp.LeaseTimeSec)
	mask := dhcp.Netmask
	if mask == "" {
		mask = "255.255.255.0"
	}
	b.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,%s\n",
		dhcp.RangeStart, dhcp.RangeEnd, mask, lease))
	b.WriteString(fmt.Sprintf("dhcp-option=option:router,%s\n", dhcp.Router))
	if len(dhcp.DNSServers) > 0 {
		b.WriteString(fmt.Sprintf("dhcp-option=option:dns-server,%s\n", strings.Join(dhcp.DNSServers, ",")))
	}
	if d := strings.TrimSpace(dhcp.Domain); d != "" {
		b.WriteString(fmt.Sprintf("domain=%s\n", d))
		b.WriteString(fmt.Sprintf("dhcp-option=option:domain-name,%s\n", d))
	}
	for _, sl := range dhcp.StaticLeases {
		line := fmt.Sprintf("dhcp-host=%s,%s", sl.MAC, sl.IP)
		if sl.Hostname != "" {
			line += "," + sl.Hostname
		}
		b.WriteString(line + "\n")
	}
	if dhcp.IPv6Enabled {
		prefix := strings.TrimSpace(dhcp.IPv6Prefix)
		start := strings.TrimSpace(dhcp.IPv6Start)
		end := strings.TrimSpace(dhcp.IPv6End)
		if prefix != "" && start != "" && end != "" {
			ra := ""
			if dhcp.RAEnabled {
				ra = ",ra-names"
				if dhcp.RAIntervalSec > 0 {
					ra += fmt.Sprintf(",ra-interval=%d", dhcp.RAIntervalSec)
				}
			}
			b.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,64%s\n", prefix, start, end, ra))
		}
	} else if dhcp.RAEnabled {
		prefix := strings.TrimSpace(dhcp.IPv6Prefix)
		if prefix != "" {
			b.WriteString(fmt.Sprintf("dhcp-range=%s,::,128,ra-only\n", prefix))
		}
	}
}

func dhcpIPv6DNSClients(dhcp store.DHCPState) bool {
	return dhcp.IPv6Enabled || dhcp.RAEnabled
}

func writeUpstreamDNSSection(b *bytes.Buffer, dhcp store.DHCPState, opts ApplyOpts) {
	if !dhcp.DNSEnabled || len(dhcp.UpstreamDNS) == 0 {
		return
	}
	if opts.Nat.DNS64UsesDnsmasqRelay() {
		return
	}
	b.WriteString("\n# qosnat2 DNS resolver upstream (dnsmasq forwarding)\n")
	for _, u := range dhcp.UpstreamDNS {
		b.WriteString(fmt.Sprintf("server=%s\n", u))
	}
	b.WriteString("no-resolv\n")
}

func writeDNS64Section(b *bytes.Buffer, dhcp store.DHCPState, opts ApplyOpts) {
	nat := opts.Nat
	if !nat.DNS64UsesDnsmasqRelay() {
		return
	}
	if nat.DNS64UsesLocalUnbound() {
		host, port, err := parseUnboundAddr(nat.DNS64.UnboundListen)
		if err != nil {
			host, port = "127.0.0.1", 5353
		}
		b.WriteString("\n# qosnat2 DNS64 via local Unbound\n")
		if !dhcp.ServiceActive() && opts.DevLAN != "" {
			b.WriteString(fmt.Sprintf("interface=%s\n", opts.DevLAN))
			b.WriteString("bind-interfaces\n")
			if v4 := strings.TrimSpace(opts.LANIPv4); v4 != "" {
				b.WriteString(fmt.Sprintf("listen-address=%s\n", v4))
			}
			b.WriteString("port=53\n")
		}
		b.WriteString(fmt.Sprintf("server=%s#%d\n", host, port))
		b.WriteString("no-resolv\n")
		if v6 := strings.TrimSpace(opts.LANIPv6); v6 != "" && dhcpIPv6DNSClients(dhcp) {
			b.WriteString(fmt.Sprintf("dhcp-option=option6:dns-server,[%s]\n", v6))
		}
		return
	}
	if nat.DNS64.Mode == store.DNS64ModeUpstream {
		up := nat.EffectiveDNS64Upstream()
		if len(up) == 0 || !dhcpIPv6DNSClients(dhcp) {
			return
		}
		var quoted []string
		for _, u := range up {
			quoted = append(quoted, "["+strings.TrimSpace(u)+"]")
		}
		b.WriteString("\n# qosnat2 DNS64 upstream resolvers\n")
		b.WriteString(fmt.Sprintf("dhcp-option=option6:dns-server,%s\n", strings.Join(quoted, ",")))
	}
}

func parseUnboundAddr(listen string) (host string, port int, err error) {
	listen = strings.TrimSpace(listen)
	if listen == "" {
		return "127.0.0.1", 5353, nil
	}
	if strings.Contains(listen, ":") {
		host, ps, ok := strings.Cut(listen, ":")
		if !ok {
			return listen, 5353, nil
		}
		var p int
		if _, e := fmt.Sscanf(ps, "%d", &p); e != nil {
			return "", 0, e
		}
		return host, p, nil
	}
	return listen, 5353, nil
}

func formatLeaseTime(sec int) string {
	if sec <= 0 {
		sec = 86400
	}
	if sec%86400 == 0 && sec >= 86400 {
		return fmt.Sprintf("%dh", sec/86400)
	}
	if sec%3600 == 0 && sec >= 3600 {
		return fmt.Sprintf("%dh", sec/3600)
	}
	return fmt.Sprintf("%ds", sec)
}

// WriteConf 写入 drop-in 配置
func WriteConf(dhcp store.DHCPState, opts ApplyOpts) error {
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(confPath, []byte(RenderConf(dhcp, opts)), 0644)
}

// Apply 写配置并 reload/start dnsmasq
func Apply(dhcp store.DHCPState, opts ApplyOpts) error {
	if !installed() {
		return fmt.Errorf("dnsmasq not installed (apt install dnsmasq)")
	}
	if err := WriteConf(dhcp, opts); err != nil {
		return err
	}
	if !dhcp.ServiceActive() && !opts.Nat.DNS64UsesDnsmasqRelay() {
		return stopService()
	}
	if err := ensureConfDirEnabled(); err != nil {
		return err
	}
	return restartService()
}

func ensureConfDirEnabled() error {
	main := "/etc/dnsmasq.conf"
	b, err := os.ReadFile(main)
	if err != nil {
		return nil
	}
	s := string(b)
	if strings.Contains(s, "conf-dir=/etc/dnsmasq.d") {
		return nil
	}
	appendLine := "\n# qosnat2: load drop-in configs\nconf-dir=/etc/dnsmasq.d/,*.conf\n"
	return os.WriteFile(main, append(b, []byte(appendLine)...), 0644)
}

func restartService() error {
	if out, err := exec.Command("systemctl", "enable", "dnsmasq").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl enable dnsmasq: %s %w", strings.TrimSpace(string(out)), err)
	}
	if out, err := exec.Command("systemctl", "restart", "dnsmasq").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart dnsmasq: %s %w", strings.TrimSpace(string(out)), err)
	}
	return waitActive(8 * time.Second)
}

func stopService() error {
	out, err := exec.Command("systemctl", "stop", "dnsmasq").CombinedOutput()
	if err != nil {
		if strings.Contains(string(out), "not found") {
			return nil
		}
		return fmt.Errorf("systemctl stop dnsmasq: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func waitActive(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		out, err := exec.Command("systemctl", "is-active", "dnsmasq").Output()
		if err == nil && strings.TrimSpace(string(out)) == "active" {
			return nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	out, _ := exec.Command("systemctl", "status", "dnsmasq", "--no-pager").CombinedOutput()
	return fmt.Errorf("dnsmasq not active after restart: %s", strings.TrimSpace(string(out)))
}

// ShowStatus 服务与租约
func ShowStatus() Status {
	st := Status{
		Installed: installed(),
		Config:    confPath,
	}
	if !st.Installed {
		return st
	}
	out, err := exec.Command("systemctl", "is-active", "dnsmasq").Output()
	st.Active = err == nil && strings.TrimSpace(string(out)) == "active"
	if b, err := os.ReadFile(leasePath); err == nil {
		st.LeasesRaw = string(b)
	}
	return st
}
