package api

import (
	"fmt"
	"os"
	"strings"
)

const defaultEnvPath = "/etc/qosnat2/env"

// ValidateEnv 启动校验：未完成引导时允许空网卡
func ValidateEnv(e Env) error {
	if e.AdminPort == "" {
		return fmt.Errorf("ADMIN_PORT required")
	}
	return nil
}

// WriteRuntimeEnv 写入 /etc/qosnat2/env（引导完成或更新网卡）
func WriteRuntimeEnv(e Env) error {
	if err := os.MkdirAll("/etc/qosnat2", 0750); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Generated by qosnat2 — do not edit unless you know what you are doing\n")
	fmt.Fprintf(&b, "ADMIN_USER=%s\n", e.AdminUser)
	if e.AdminPass != "" {
		fmt.Fprintf(&b, "ADMIN_PASS=%s\n", e.AdminPass)
	}
	fmt.Fprintf(&b, "ADMIN_PORT=%s\n", e.AdminPort)
	fmt.Fprintf(&b, "DEV_LAN=%s\n", e.DevLAN)
	fmt.Fprintf(&b, "DEV_WAN=%s\n", e.DevWAN)
	if e.StateFile != "" {
		fmt.Fprintf(&b, "STATE_FILE=%s\n", e.StateFile)
	}
	if e.SessionFile != "" {
		fmt.Fprintf(&b, "SESSION_FILE=%s\n", e.SessionFile)
	}
	if e.OpenAPIPath != "" {
		fmt.Fprintf(&b, "OPENAPI_PATH=%s\n", e.OpenAPIPath)
	}
	if e.WebRoot != "" {
		fmt.Fprintf(&b, "WEB_ROOT=%s\n", e.WebRoot)
	}
	return os.WriteFile(defaultEnvPath, []byte(b.String()), 0600)
}
