package unbound

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	confPath = "/etc/unbound/unbound.conf.d/qosnat2-dns64.conf"
)

// RenderOpts 运行期网关地址与 ACL
type RenderOpts struct {
	GatewayIPv4  string
	AccessAllow  []string
}

// Installed reports whether unbound is available
func Installed() bool {
	_, err := exec.LookPath("unbound")
	return err != nil
}

// Render 生成 DNS64 Unbound 片段
func Render(nat store.NatState, opts RenderOpts) (string, error) {
	if !nat.DNS64UsesLocalUnbound() {
		return "", nil
	}
	host, port, err := nat.DNS64.EffectiveUnboundListen(opts.GatewayIPv4)
	if err != nil {
		return "", err
	}
	prefix := strings.TrimSpace(nat.Nat64Prefix)
	if prefix == "" {
		prefix = store.DefaultNat64Prefix
	}
	var b strings.Builder
	b.WriteString("# Generated by qosnat2 — do not edit manually\n")
	b.WriteString("server:\n")
	b.WriteString(fmt.Sprintf("    interface: %s\n", host))
	b.WriteString(fmt.Sprintf("    port: %d\n", port))
	b.WriteString("    do-ip4: yes\n")
	b.WriteString("    do-ip6: yes\n")
	if nat.DNS64.ServeToClients {
		b.WriteString("    access-control: 127.0.0.0/8 allow\n")
		b.WriteString("    access-control: ::1 allow\n")
	} else {
		for _, cidr := range opts.AccessAllow {
			b.WriteString(fmt.Sprintf("    access-control: %s allow\n", cidr))
		}
		if len(opts.AccessAllow) == 0 {
			b.WriteString("    access-control: 0.0.0.0/0 allow\n")
			b.WriteString("    access-control: ::/0 allow\n")
		}
	}
	b.WriteString("    module-config: \"dns64 validator iterator\"\n")
	b.WriteString(fmt.Sprintf("    dns64-prefix: %s\n", prefix))
	var fwdAddrs []string
	for _, fwd := range nat.DNS64.Forwarders {
		fwd = strings.TrimSpace(fwd)
		if fwd != "" {
			fwdAddrs = append(fwdAddrs, fwd)
		}
	}
	if len(fwdAddrs) > 0 {
		b.WriteString("forward-zone:\n")
		b.WriteString("    name: \".\"\n")
		for _, fwd := range fwdAddrs {
			b.WriteString(fmt.Sprintf("    forward-addr: %s@53\n", fwd))
		}
	}
	return b.String(), nil
}

// Apply 写入配置并 reload unbound
func Apply(nat store.NatState, opts RenderOpts) error {
	if !nat.Nat64Enabled || nat.DNS64.Mode != store.DNS64ModeLocal {
		return removeConf()
	}
	if !Installed() {
		return fmt.Errorf("unbound not installed (apt install unbound)")
	}
	body, err := Render(nat, opts)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(confPath, []byte(body), 0644); err != nil {
		return err
	}
	if out, err := exec.Command("systemctl", "enable", "unbound").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl enable unbound: %s %w", strings.TrimSpace(string(out)), err)
	}
	if out, err := exec.Command("systemctl", "restart", "unbound").CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart unbound: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func removeConf() error {
	if err := os.Remove(confPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	if !Installed() {
		return nil
	}
	_, _ = exec.Command("systemctl", "try-restart", "unbound").CombinedOutput()
	return nil
}

// Active 检查 unbound 是否在运行
func Active() bool {
	if !Installed() {
		return false
	}
	out, err := exec.Command("systemctl", "is-active", "unbound").Output()
	return err == nil && strings.TrimSpace(string(out)) == "active"
}

// ListenSummary 供 API 状态展示
func ListenSummary(nat store.NatState, gatewayIPv4 string) string {
	host, port, err := nat.DNS64.EffectiveUnboundListen(gatewayIPv4)
	if err != nil {
		return ""
	}
	if strings.Contains(host, ":") {
		return fmt.Sprintf("[%s]:%d", host, port)
	}
	return fmt.Sprintf("%s:%d", host, port)
}
