package snmpd

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	managedConf  = "/etc/qosnat2/snmpd.conf"
	backupConf   = "/etc/snmp/snmpd.conf.bak.qosnat2"
	runtimeConf  = "/etc/snmp/snmpd.conf"
	serviceName  = "snmpd"
)

// Status snmpd 运行状态。
type Status struct {
	Installed bool   `json:"installed"`
	Active    bool   `json:"active"`
	Config    string `json:"config_path"`
	Version   string `json:"version,omitempty"`
}

func installed() bool {
	_, err := exec.LookPath("snmpd")
	return err == nil
}

// ShowStatus 返回安装与运行状态。
func ShowStatus() Status {
	st := Status{
		Installed: installed(),
		Config:    managedConf,
	}
	if !st.Installed {
		return st
	}
	if out, err := exec.Command("snmpd", "-v").CombinedOutput(); err == nil {
		line := strings.TrimSpace(strings.Split(string(out), "\n")[0])
		st.Version = line
	}
	out, err := exec.Command("systemctl", "is-active", serviceName).Output()
	st.Active = err == nil && strings.TrimSpace(string(out)) == "active"
	return st
}

// RenderConf 生成完整 snmpd.conf（qosnat2 托管）。
func RenderConf(s store.SNMPState) string {
	var b strings.Builder
	b.WriteString("# Generated by qosnat2 — do not edit manually\n")
	if !s.Enabled {
		b.WriteString("# snmpd disabled by qosnat2\n")
		return b.String()
	}
	if s.SysLocation != "" {
		b.WriteString("sysLocation ")
		b.WriteString(s.SysLocation)
		b.WriteByte('\n')
	}
	if s.SysContact != "" {
		b.WriteString("sysContact ")
		b.WriteString(s.SysContact)
		b.WriteByte('\n')
	}
	if s.SysName != "" {
		b.WriteString("sysName ")
		b.WriteString(s.SysName)
		b.WriteByte('\n')
	}
	port := s.Port
	if port <= 0 {
		port = 161
	}
	if s.ListenLocalhostOnly {
		fmt.Fprintf(&b, "agentAddress udp:127.0.0.1:%d\n", port)
	} else {
		fmt.Fprintf(&b, "agentAddress udp:0.0.0.0:%d,udp6:[::1]:%d\n", port, port)
	}
	b.WriteString(systemOnlyViewBlock())
	community := s.ROCommunity
	for _, cidr := range s.AllowedNetworks {
		fmt.Fprintf(&b, "rocommunity %s %s -V systemonly\n", community, cidr)
	}
	return b.String()
}

func systemOnlyViewBlock() string {
	return `view systemonly included .1.3.6.1.2.1.1
view systemonly included .1.3.6.1.2.1.25.1.1
view systemonly included .1.3.6.1.4.1.2021.4
view systemonly included .1.3.6.1.4.1.2021.6
view systemonly included .1.3.6.1.4.1.2021.10
view systemonly included .1.3.6.1.4.1.2021.11
`
}

// Install apt 安装 snmpd。
func Install() error {
	if installed() {
		return nil
	}
	out, err := exec.Command("apt-get", "install", "-y", "-qq", "snmpd").CombinedOutput()
	if err != nil {
		return fmt.Errorf("apt install snmpd: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// Apply 写入配置并启停 snmpd。
func Apply(s store.SNMPState) error {
	if !installed() {
		return fmt.Errorf("snmpd not installed (apt install snmpd)")
	}
	body := RenderConf(s)
	if err := os.MkdirAll(filepath.Dir(managedConf), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(managedConf, []byte(body), 0644); err != nil {
		return err
	}
	if !s.Enabled {
		return stopService()
	}
	if err := backupMainIfNeeded(); err != nil {
		return err
	}
	if err := os.WriteFile(runtimeConf, []byte(body), 0644); err != nil {
		return err
	}
	return restartService()
}

func backupMainIfNeeded() error {
	if _, err := os.Stat(backupConf); err == nil {
		return nil
	}
	src, err := os.Open(runtimeConf)
	if err != nil {
		return nil
	}
	defer src.Close()
	dst, err := os.Create(backupConf)
	if err != nil {
		return err
	}
	_, cpErr := io.Copy(dst, src)
	closeErr := dst.Close()
	if cpErr != nil {
		return cpErr
	}
	return closeErr
}

func restartService() error {
	if out, err := exec.Command("systemctl", "enable", serviceName).CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl enable %s: %s %w", serviceName, strings.TrimSpace(string(out)), err)
	}
	if out, err := exec.Command("systemctl", "restart", serviceName).CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart %s: %s %w", serviceName, strings.TrimSpace(string(out)), err)
	}
	return waitActive(8 * time.Second)
}

func stopService() error {
	out, err := exec.Command("systemctl", "stop", serviceName).CombinedOutput()
	if err != nil {
		if strings.Contains(string(out), "not loaded") || strings.Contains(string(out), "not found") {
			return nil
		}
		return fmt.Errorf("systemctl stop %s: %s %w", serviceName, strings.TrimSpace(string(out)), err)
	}
	return nil
}

// ServiceAction start|stop|restart。
func ServiceAction(action string) error {
	if !installed() {
		return fmt.Errorf("snmpd not installed")
	}
	switch action {
	case "start", "stop", "restart":
	default:
		return fmt.Errorf("invalid action: %s", action)
	}
	out, err := exec.Command("systemctl", action, serviceName).CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %s %s: %s %w", action, serviceName, strings.TrimSpace(string(out)), err)
	}
	return nil
}

func waitActive(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		out, err := exec.Command("systemctl", "is-active", serviceName).Output()
		if err == nil && strings.TrimSpace(string(out)) == "active" {
			return nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	out, _ := exec.Command("systemctl", "status", serviceName, "--no-pager").CombinedOutput()
	return fmt.Errorf("snmpd not active after restart: %s", strings.TrimSpace(string(out)))
}
