package frr

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

const DynamicRoutingConfig = Dir + "/dynamic-routing.conf"
const dynamicApplyScript = Dir + "/dynamic-routing-apply.vtysh"

// RenderDynamic 生成 FRR 原生配置（供 include 与 vtysh 回放）。
func RenderDynamic(dr store.DynamicRoutingState) string {
	var b strings.Builder
	b.WriteString("! generated by qosnat2 — dynamic routing\n")
	renderBGPConfig(&b, dr.BGP)
	renderOSPFConfig(&b, dr.OSPF)
	return b.String()
}

// RenderDynamicApplyScript 生成 vtysh 批量应用脚本（先清理再写入）。
func RenderDynamicApplyScript(dr store.DynamicRoutingState) string {
	var b strings.Builder
	b.WriteString("configure terminal\n")
	b.WriteString("no router bgp\n")
	b.WriteString("no router ospf\n")
	if dr.BGP.Enabled {
		writeBGPVTY(&b, dr.BGP)
	}
	if dr.OSPF.Enabled {
		writeOSPFVTY(&b, dr.OSPF)
	}
	b.WriteString("end\n")
	b.WriteString("write memory\n")
	return b.String()
}

func renderBGPConfig(b *strings.Builder, cfg store.BGPConfig) {
	if !cfg.Enabled || cfg.ASN == 0 {
		return
	}
	fmt.Fprintf(b, "!\nrouter bgp %d\n", cfg.ASN)
	if cfg.RouterID != "" {
		fmt.Fprintf(b, " bgp router-id %s\n", cfg.RouterID)
	}
	for _, n := range cfg.Neighbors {
		if !n.Enabled {
			continue
		}
		fmt.Fprintf(b, " neighbor %s remote-as %d\n", n.Address, n.RemoteASN)
		if n.Description != "" {
			fmt.Fprintf(b, " neighbor %s description %s\n", n.Address, quoteDesc(n.Description))
		}
		if n.Password != "" {
			fmt.Fprintf(b, " neighbor %s password %s\n", n.Address, n.Password)
		}
		if n.UpdateSource != "" {
			fmt.Fprintf(b, " neighbor %s update-source %s\n", n.Address, n.UpdateSource)
		}
	}
	b.WriteString(" !\n address-family ipv4 unicast\n")
	for _, n := range cfg.Neighbors {
		if n.Enabled {
			fmt.Fprintf(b, "  neighbor %s activate\n", n.Address)
		}
	}
	for _, cidr := range cfg.Networks {
		fmt.Fprintf(b, "  network %s\n", cidr)
	}
	if cfg.RedistributeConnected {
		b.WriteString("  redistribute connected\n")
	}
	b.WriteString(" exit-address-family\n")
	b.WriteString("!\n")
}

func renderOSPFConfig(b *strings.Builder, cfg store.OSPFConfig) {
	if !cfg.Enabled {
		return
	}
	b.WriteString("!\nrouter ospf\n")
	if cfg.RouterID != "" {
		fmt.Fprintf(b, " ospf router-id %s\n", cfg.RouterID)
	}
	for _, n := range cfg.Networks {
		if !n.Enabled {
			continue
		}
		area := n.Area
		if area == "" {
			area = "0.0.0.0"
		}
		fmt.Fprintf(b, " network %s area %s\n", n.Prefix, area)
	}
	if cfg.RedistributeConnected {
		b.WriteString(" redistribute connected\n")
	}
	b.WriteString("!\n")
}

func writeBGPVTY(b *strings.Builder, cfg store.BGPConfig) {
	fmt.Fprintf(b, "router bgp %d\n", cfg.ASN)
	if cfg.RouterID != "" {
		fmt.Fprintf(b, " bgp router-id %s\n", cfg.RouterID)
	}
	for _, n := range cfg.Neighbors {
		if !n.Enabled {
			continue
		}
		fmt.Fprintf(b, " neighbor %s remote-as %d\n", n.Address, n.RemoteASN)
		if n.Description != "" {
			fmt.Fprintf(b, " neighbor %s description %s\n", n.Address, quoteDesc(n.Description))
		}
		if n.Password != "" {
			fmt.Fprintf(b, " neighbor %s password %s\n", n.Address, n.Password)
		}
		if n.UpdateSource != "" {
			fmt.Fprintf(b, " neighbor %s update-source %s\n", n.Address, n.UpdateSource)
		}
	}
	b.WriteString(" address-family ipv4 unicast\n")
	for _, n := range cfg.Neighbors {
		if n.Enabled {
			fmt.Fprintf(b, "  neighbor %s activate\n", n.Address)
		}
	}
	for _, cidr := range cfg.Networks {
		fmt.Fprintf(b, "  network %s\n", cidr)
	}
	if cfg.RedistributeConnected {
		b.WriteString("  redistribute connected\n")
	}
	b.WriteString(" exit-address-family\n")
}

func writeOSPFVTY(b *strings.Builder, cfg store.OSPFConfig) {
	b.WriteString("router ospf\n")
	if cfg.RouterID != "" {
		fmt.Fprintf(b, " ospf router-id %s\n", cfg.RouterID)
	}
	for _, n := range cfg.Networks {
		if !n.Enabled {
			continue
		}
		area := n.Area
		if area == "" {
			area = "0.0.0.0"
		}
		fmt.Fprintf(b, " network %s area %s\n", n.Prefix, area)
	}
	if cfg.RedistributeConnected {
		b.WriteString(" redistribute connected\n")
	}
}

func quoteDesc(s string) string {
	if strings.ContainsAny(s, " \t\n\r\"'") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

// ApplyDynamic 写入动态路由配置、同步 daemons 并通过 vtysh 应用。
func ApplyDynamic(dr store.DynamicRoutingState) error {
	if err := os.MkdirAll(Dir, 0755); err != nil {
		return err
	}
	native := RenderDynamic(dr)
	if err := os.WriteFile(DynamicRoutingConfig, []byte(native), 0644); err != nil {
		return err
	}
	if err := ensureInclude(); err != nil {
		return err
	}
	restarted, err := SyncDaemons(store.DynamicRoutingNeedsBGP(dr), store.DynamicRoutingNeedsOSPF(dr))
	if err != nil {
		return err
	}
	if !PackageInstalled() {
		return nil
	}
	if restarted {
		return nil
	}
	if !ServiceActive() {
		return nil
	}
	script := RenderDynamicApplyScript(dr)
	if err := os.WriteFile(dynamicApplyScript, []byte(script), 0600); err != nil {
		return err
	}
	if err := runVTYSH(script); err != nil {
		return fmt.Errorf("vtysh dynamic apply: %w", err)
	}
	return nil
}

// DynamicStatus 解析 BGP/OSPF 运行摘要（FRR 未运行或未安装时返回空字段）。
func DynamicStatus(dr store.DynamicRoutingState) map[string]any {
	st := map[string]any{
		"bgp":  map[string]any{"enabled": dr.BGP.Enabled, "summary": "", "neighbors": []any{}},
		"ospf": map[string]any{"enabled": dr.OSPF.Enabled, "summary": "", "neighbors": []any{}},
	}
	if !PackageInstalled() || !ServiceActive() {
		return st
	}
	if dr.BGP.Enabled {
		st["bgp"] = parseBGPSummary()
	}
	if dr.OSPF.Enabled {
		st["ospf"] = parseOSPFSummary()
	}
	return st
}

func parseBGPSummary() map[string]any {
	out := map[string]any{"summary": "", "neighbors": []map[string]string{}}
	raw, err := exec.Command("vtysh", "-c", "show ip bgp summary").CombinedOutput()
	if err != nil {
		out["summary"] = strings.TrimSpace(string(raw))
		return out
	}
	text := string(raw)
	out["summary"] = strings.TrimSpace(text)
	out["neighbors"] = parseBGPNeighborTable(text)
	return out
}

func parseOSPFSummary() map[string]any {
	out := map[string]any{"summary": "", "neighbors": []map[string]string{}}
	raw, err := exec.Command("vtysh", "-c", "show ip ospf neighbor").CombinedOutput()
	if err != nil {
		out["summary"] = strings.TrimSpace(string(raw))
		return out
	}
	text := string(raw)
	out["summary"] = strings.TrimSpace(text)
	out["neighbors"] = parseOSPFNeighborTable(text)
	return out
}

func parseBGPNeighborTable(text string) []map[string]string {
	var rows []map[string]string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "Neighbor") || strings.HasPrefix(line, "-") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 9 {
			continue
		}
		rows = append(rows, map[string]string{
			"neighbor": fields[0],
			"v":        fields[1],
			"as":       fields[2],
			"state":    fields[9],
		})
	}
	return rows
}

func parseOSPFNeighborTable(text string) []map[string]string {
	var rows []map[string]string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "Neighbor") || strings.HasPrefix(line, "-") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 6 {
			continue
		}
		rows = append(rows, map[string]string{
			"neighbor_id": fields[0],
			"priority":    fields[1],
			"state":       fields[2],
			"dead_time":   fields[3],
			"address":     fields[4],
			"interface":   fields[5],
		})
	}
	return rows
}
