package frr

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	Dir              = "/etc/qosnat2/frr"
	ManagedRoutes    = Dir + "/managed-routes.conf"
	ExtraConfig      = Dir + "/extra.conf"
	IncludeSnippet   = "/etc/frr/frr.conf.d/qosnat2.conf"
	mainIncludeLine  = "include " + IncludeSnippet
	ApplyVTYSHScript = Dir + "/apply.vtysh"
)

// Installed 报告 frr 包与 systemd 单元是否可用（兼容旧调用）。
func Installed() bool {
	return PackageInstalled() && ServiceActive()
}

func EditableConfigKeys() []string {
	return []string{"frr.conf", "extra", "managed", "dynamic", "daemons", "include"}
}

// RenderManaged 从 qosnat2 托管路由生成 FRR 原生配置（frr.conf / include 语法）。
func RenderManaged(routes []store.RouteEntry) (string, error) {
	var b strings.Builder
	b.WriteString("! generated by qosnat2 — do not edit\n")
	for _, r := range routes {
		if !r.Enabled {
			continue
		}
		lines, err := routeVTYLines(r)
		if err != nil {
			return "", fmt.Errorf("%s: %w", r.ID, err)
		}
		for _, ln := range lines {
			b.WriteString(ln)
			b.WriteByte('\n')
		}
	}
	return b.String(), nil
}

func renderManagedVTYApply(prevNative, newNative string) string {
	prevLines := extractIPRouteLines(prevNative)
	newLines := extractIPRouteLines(newNative)
	var script strings.Builder
	script.WriteString("configure terminal\n")
	for _, ln := range prevLines {
		script.WriteString("no ")
		script.WriteString(ln)
		script.WriteByte('\n')
	}
	for _, ln := range newLines {
		script.WriteString(ln)
		script.WriteByte('\n')
	}
	script.WriteString("end\nwrite memory\n")
	return script.String()
}

func routeVTYLines(r store.RouteEntry) ([]string, error) {
	dest, err := store.NormalizeRouteDest(r.Dest)
	if err != nil {
		return nil, err
	}
	if dest == "default" {
		dest = "0.0.0.0/0"
	}
	table := r.Table
	suffix := ""
	if table > 0 && table != 254 {
		suffix = fmt.Sprintf(" table %d", table)
	}
	var out []string
	if len(r.Nexthops) > 0 {
		for _, nh := range r.Nexthops {
			ln, err := singleVTYLine(dest, nh.Gateway, nh.Device, nh.Weight, suffix)
			if err != nil {
				return nil, err
			}
			out = append(out, ln)
		}
		return out, nil
	}
	ln, err := singleVTYLine(dest, r.Gateway, r.Device, 0, suffix)
	if err != nil {
		return nil, err
	}
	return []string{ln}, nil
}

func singleVTYLine(dest, gw, dev string, _ int, tableSuffix string) (string, error) {
	gw = strings.TrimSpace(gw)
	dev = strings.TrimSpace(dev)
	if gw == "" && dev == "" {
		return "", fmt.Errorf("route requires gateway or device")
	}
	var nh string
	if gw != "" && dev != "" {
		nh = fmt.Sprintf("%s %s", gw, dev)
	} else if gw != "" {
		nh = gw
	} else {
		nh = dev
	}
	line := fmt.Sprintf("ip route %s %s%s", dest, nh, tableSuffix)
	return line, nil
}

// extractIPRouteLines 从托管配置或 vtysh 脚本中提取 ip route 行。
func extractIPRouteLines(text string) []string {
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "ip route ") {
			out = append(out, line)
		}
	}
	return out
}

// ApplyManaged 写入托管路由并 reload FRR（先撤销旧托管项再写入，避免残留）。
func ApplyManaged(routes []store.RouteEntry) error {
	body, err := RenderManaged(routes)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(Dir, 0755); err != nil {
		return err
	}
	prev, _ := os.ReadFile(ManagedRoutes)
	scriptBody := renderManagedVTYApply(string(prev), body)
	if err := os.WriteFile(ManagedRoutes, []byte(body), 0644); err != nil {
		return err
	}
	if err := ensureInclude(); err != nil {
		return err
	}
	if err := ensureMainConfInclude(); err != nil {
		return err
	}
	if err := os.WriteFile(ApplyVTYSHScript, []byte(scriptBody), 0600); err != nil {
		return err
	}
	if err := runVTYSH(scriptBody); err != nil {
		return fmt.Errorf("vtysh apply: %w", err)
	}
	return nil
}

func ensureInclude() error {
	if err := os.MkdirAll(filepath.Dir(IncludeSnippet), 0755); err != nil {
		return err
	}
	var lines []string
	lines = append(lines, "include "+ManagedRoutes)
	lines = append(lines, "include "+DynamicRoutingConfig)
	if extra, err := os.ReadFile(ExtraConfig); err == nil && strings.TrimSpace(string(extra)) != "" {
		lines = append(lines, "include "+ExtraConfig)
	}
	includeBody := "! qosnat2 managed FRR includes\n"
	for _, ln := range lines {
		includeBody += ln + "\n"
	}
	cur, err := os.ReadFile(IncludeSnippet)
	if err == nil && string(cur) == includeBody {
		return ensureMainConfInclude()
	}
	if err := os.WriteFile(IncludeSnippet, []byte(includeBody), 0644); err != nil {
		return err
	}
	return ensureMainConfInclude()
}

// ensureMainConfInclude 保证 /etc/frr/frr.conf 引用 qosnat2 include，以便 FRR 冷启动加载托管路由。
func ensureMainConfInclude() error {
	if !PackageInstalled() {
		return nil
	}
	b, err := os.ReadFile(FRRConfPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	content := string(b)
	if strings.Contains(content, IncludeSnippet) || strings.Contains(content, "frr.conf.d/qosnat2.conf") {
		return nil
	}
	var out strings.Builder
	out.WriteString(strings.TrimRight(content, "\n"))
	out.WriteByte('\n')
	out.WriteString(mainIncludeLine)
	out.WriteByte('\n')
	return os.WriteFile(FRRConfPath, []byte(out.String()), 0644)
}

// PrepareInstalled 在 FRR 包安装后写入 include 并挂接到主 frr.conf。
func PrepareInstalled() error {
	if !PackageInstalled() {
		return nil
	}
	if err := ensureInclude(); err != nil {
		return err
	}
	return ensureMainConfInclude()
}

// ReadExtra 读取用户附加 FRR 配置。
func ReadExtra() (string, error) {
	b, err := os.ReadFile(ExtraConfig)
	if os.IsNotExist(err) {
		return "", nil
	}
	return string(b), err
}

// WriteExtra 保存用户附加 FRR 配置（vtysh/frr.conf 语法）。
func WriteExtra(body string) error {
	if err := os.MkdirAll(Dir, 0755); err != nil {
		return err
	}
	if strings.TrimSpace(body) == "" {
		_ = os.Remove(ExtraConfig)
		return ensureInclude()
	}
	if err := os.WriteFile(ExtraConfig, []byte(body), 0644); err != nil {
		return err
	}
	return ensureInclude()
}
