package nft

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/hk59775634/qosnat2/internal/netif"
	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	RulesPath = "/etc/qosnat2/nftables-qosnat.nft"
	TableName = "qosnat"
)

// Config 运行期网卡名与管理端口（来自环境变量 / state）
type Config struct {
	DevLAN    string
	DevWAN    string
	AdminPort string
	VPN       VPNFirewall
}

// ResolveSharedIPs 返回生效的共享 SNAT 地址：未配置时使用 WAN 口首个全球 IPv4
func ResolveSharedIPs(cfg Config, st store.State) (ips []string, autoFromWAN bool) {
	if len(st.Nat.IPv4.SharedIPs) > 0 {
		return append([]string(nil), st.Nat.IPv4.SharedIPs...), false
	}
	if cfg.DevWAN == "" {
		return nil, false
	}
	ip, err := netif.PrimaryIPv4(cfg.DevWAN)
	if err != nil || ip == "" {
		return nil, false
	}
	return []string{ip}, true
}

// Render 根据 state 生成 inet qosnat 规则（无 flowtable，宿主机 WAN）
func Render(cfg Config, st store.State) (string, error) {
	if cfg.DevWAN == "" {
		return "", fmt.Errorf("DEV_WAN required")
	}
	st.Firewall.FilterRules, _ = store.SyncAutoFilterRules(
		st.Firewall.FilterRules,
		cfg.DevWAN,
		cfg.AdminPort,
		store.AutoInputVPN{
			OCServEnabled: cfg.VPN.OCServEnabled,
			OCServTCP:     cfg.VPN.OCServTCP,
			OCServUDP:     cfg.VPN.OCServUDP,
			WGPorts:       cfg.VPN.WGPorts,
		},
	)
	routes := st.Nat.IPv4.PolicyRoutes
	if len(routes) == 0 {
		routes = []string{st.Shaper.PolicyCIDR}
	}
	if len(routes) == 0 {
		routes = []string{"10.0.0.0/8"}
	}
	egressCIDRs := store.EgressPolicyCIDRs(st.Network.EgressPolicies)
	routes = store.FilterPolicyRoutesForWAN(routes, egressCIDRs)
	egress := store.ResolveEgressPolicies(st, netif.PrimaryIPv4)
	ips, _ := ResolveSharedIPs(cfg, st)

	var b strings.Builder
	b.WriteString("# qosnat2 — generated by qosnatd\n")
	b.WriteString("# mark 隔离: 禁止 meta mark set / flowtable；QoS 用 tc_classid，IFB 用 bpf_redirect\n")
	b.WriteString("flush ruleset\n\n")
	b.WriteString(fmt.Sprintf("table inet %s {\n", TableName))
	writeAliasSets(&b, st.Firewall.Aliases)

	// prerouting DNAT
	b.WriteString("    chain prerouting {\n")
	b.WriteString("        type nat hook prerouting priority dstnat; policy accept;\n")
	writeWanForwardRules(&b, cfg, st.Firewall.WanPortForwards)
	writeNPTv6Prerouting(&b, st.Nat)
	b.WriteString("    }\n\n")

	// postrouting SNAT
	b.WriteString("    chain postrouting {\n")
	b.WriteString("        type nat hook postrouting priority srcnat; policy accept;\n")
	staticKeys := sortedKeys(st.Nat.IPv4.StaticMappings)
	for _, inner := range staticKeys {
		b.WriteString(fmt.Sprintf("        ip saddr %s snat to %s\n", inner, st.Nat.IPv4.StaticMappings[inner]))
	}
	if len(st.Nat.IPv4.PrefixMappings) > 0 {
		b.WriteString(fmt.Sprintf("        oifname \"%s\" snat ip prefix to ip saddr map {\n", cfg.DevWAN))
		for _, inner := range sortedKeys(st.Nat.IPv4.PrefixMappings) {
			b.WriteString(fmt.Sprintf("            %s : %s,\n", inner, st.Nat.IPv4.PrefixMappings[inner]))
		}
		b.WriteString("        }\n")
	}
	writeNPTv6Postrouting(&b, cfg, st.Nat)
	for _, e := range egress {
		if e.Masquerade {
			b.WriteString(fmt.Sprintf(
				"        ip saddr %s oifname \"%s\" masquerade\n",
				e.Policy.CIDR, e.Device,
			))
			continue
		}
		b.WriteString(fmt.Sprintf(
			"        ip saddr %s oifname \"%s\" snat to %s\n",
			e.Policy.CIDR, e.Device, e.SNATIP,
		))
	}
	if len(ips) > 0 {
		var inline []string
		for i, ip := range ips {
			inline = append(inline, fmt.Sprintf("%d : %s", i, ip))
		}
		for _, cidr := range routes {
			b.WriteString(fmt.Sprintf(
				"        ip saddr %s oifname \"%s\" snat to numgen inc mod %d map { %s }\n",
				cidr, cfg.DevWAN, len(ips), strings.Join(inline, ", "),
			))
		}
	} else {
		for _, cidr := range routes {
			b.WriteString(fmt.Sprintf(
				"        ip saddr %s oifname \"%s\" masquerade\n",
				cidr, cfg.DevWAN,
			))
		}
	}
	b.WriteString(fmt.Sprintf("        oifname \"%s\" masquerade\n", cfg.DevWAN))
	b.WriteString("    }\n\n")

	// forward filter
	b.WriteString("    chain forward {\n")
	b.WriteString("        type filter hook forward priority filter; policy accept;\n")
	b.WriteString("        ct state established,related accept\n")
	writeFilterRules(&b, "forward", st.Firewall.FilterRules)
	wanDevs := map[string]struct{}{cfg.DevWAN: {}}
	for _, e := range egress {
		wanDevs[e.Device] = struct{}{}
	}
	if cfg.DevLAN != "" {
		for dev := range wanDevs {
			if dev == "" || dev == cfg.DevLAN {
				continue
			}
			b.WriteString(fmt.Sprintf("        iifname \"%s\" oifname \"%s\" accept\n", cfg.DevLAN, dev))
			b.WriteString(fmt.Sprintf("        iifname \"%s\" oifname \"%s\" accept\n", dev, cfg.DevLAN))
		}
		// 非对称回程：公网源直达 LAN 内网段丢弃
		allPolicyCIDRs := append(append([]string{}, routes...), egressCIDRs...)
		for _, cidr := range allPolicyCIDRs {
			for dev := range wanDevs {
				if dev == "" || dev == cfg.DevLAN {
					continue
				}
				b.WriteString(fmt.Sprintf(
					"        iifname \"%s\" oifname \"%s\" ip daddr %s ip saddr != %s drop\n",
					dev, cfg.DevLAN, cidr, cidr,
				))
			}
		}
	}
	b.WriteString("    }\n\n")

	// input（基础）
	b.WriteString("    chain input {\n")
	b.WriteString("        type filter hook input priority filter; policy accept;\n")
	b.WriteString("        iifname \"lo\" accept\n")
	b.WriteString("        ct state established,related accept\n")
	writeFilterRules(&b, "input", st.Firewall.FilterRules)
	if cfg.DevLAN != "" {
		b.WriteString(fmt.Sprintf("        iifname \"%s\" accept\n", cfg.DevLAN))
	}
	// IFB 上行整形（mirred 重定向）须放行入站，否则 u32/BPF 路径异常。
	b.WriteString("        iifname \"ifb0\" accept\n")
	if st.System.AcmeTempAllowHTTP01 {
		// ACME http-01 挑战需要公网 80 端口可达；临时放开所有接口 tcp/80 入站。
		b.WriteString("        tcp dport 80 accept comment \"qosnat2-acme-http01-open80\"\n")
	}
	// WAN 管理/VPN/按口丢弃：由 store.SyncAutoFilterRules（auto-*）在上方 filter_rules 输出。
	// 除 lo、LAN、ifb0 及已匹配的 WAN 放行项外，其余网卡入站一律丢弃。
	b.WriteString("        drop comment \"qosnat2-input-default-deny\"\n")
	b.WriteString("    }\n}\n")
	return b.String(), nil
}

// Apply 生成、校验并加载 nftables
func Apply(cfg Config, st store.State) error {
	body, err := Render(cfg, st)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(RulesPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(RulesPath, []byte(body), 0644); err != nil {
		return err
	}
	if out, err := exec.Command("nft", "-c", "-f", RulesPath).CombinedOutput(); err != nil {
		return fmt.Errorf("nft check: %s %w", strings.TrimSpace(string(out)), err)
	}
	if out, err := exec.Command("nft", "-f", RulesPath).CombinedOutput(); err != nil {
		return fmt.Errorf("nft load: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// RemoveSharedIP 删除共享 IP
func RemoveSharedIP(st *store.State, ip string) bool {
	var out []string
	found := false
	for _, e := range st.Nat.IPv4.SharedIPs {
		if e == ip {
			found = true
			continue
		}
		out = append(out, e)
	}
	st.Nat.IPv4.SharedIPs = out
	return found
}

// AddSharedIP 追加共享 IP（API 用）
func AddSharedIP(st *store.State, ip string) error {
	if netParseIP(ip) != nil {
		return fmt.Errorf("invalid ip: %s", ip)
	}
	for _, e := range st.Nat.IPv4.SharedIPs {
		if e == ip {
			return nil
		}
	}
	st.Nat.IPv4.SharedIPs = append(st.Nat.IPv4.SharedIPs, ip)
	return nil
}

func netParseIP(s string) error {
	parts := strings.Split(s, ".")
	if len(parts) != 4 {
		return fmt.Errorf("bad ip")
	}
	for _, p := range parts {
		n, err := strconv.Atoi(p)
		if err != nil || n < 0 || n > 255 {
			return fmt.Errorf("bad ip")
		}
	}
	return nil
}
