package nft

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"

	"github.com/hk59775634/qosnat2/internal/netif"
	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	RulesPath       = "/etc/qosnat2/nftables-qosnat.nft"
	RulesBackupPath = "/etc/qosnat2/nftables-qosnat.live.bak.nft"
	TableName       = "qosnat"
)

// Config 运行期网卡名与管理端口（来自环境变量 / state）
type Config struct {
	DevLAN    string
	DevWAN    string
	AdminPort string
	VPN       VPNFirewall
}

// ResolveSharedIPs 返回生效的共享 SNAT 地址：未配置时使用 WAN 口首个全球 IPv4
func ResolveSharedIPs(cfg Config, st store.State) (ips []string, autoFromWAN bool) {
	if len(st.Nat.IPv4.SharedIPs) > 0 {
		return append([]string(nil), st.Nat.IPv4.SharedIPs...), false
	}
	if cfg.DevWAN == "" {
		return nil, false
	}
	ip, err := netif.PrimaryIPv4(cfg.DevWAN)
	if err != nil || ip == "" {
		return nil, false
	}
	return []string{ip}, true
}

// Render 根据 state 生成 inet qosnat 规则（无 flowtable，宿主机 WAN）
func Render(cfg Config, st store.State) (string, error) {
	if cfg.DevWAN == "" {
		return "", fmt.Errorf("DEV_WAN required")
	}
	wanInputDevs := store.CollectWanInputDevices(cfg.DevWAN, cfg.DevLAN, st)
	st.Firewall.FilterRules, _ = store.SyncAutoFilterRules(
		st.Firewall.FilterRules,
		wanInputDevs,
		cfg.AdminPort,
		AutoInputFromState(st),
		st.Firewall.WanPortForwards,
		st.LVS,
		cfg.DevLAN,
		cfg.DevWAN,
		HairpinAddrResolver(cfg.DevLAN, cfg.DevWAN),
	)
	routes := st.Nat.IPv4.PolicyRoutes
	egressCIDRs := store.EgressPolicyCIDRs(st.Network.EgressPolicies)
	snatEgressCIDRs := store.EgressPolicySnatSourceCIDRs(st.Network.EgressPolicies)
	natOn := store.NatIPv4Enabled(st.Nat.IPv4)
	if natOn {
		routes = store.FilterPolicyRoutesForWAN(routes, egressCIDRs)
	} else {
		routes = nil
		egressCIDRs = nil
		snatEgressCIDRs = nil
	}
	egress := store.ResolveEgressPolicies(st, netif.PrimaryIPv4)
	if !natOn {
		egress = nil
	}
	ips, _ := ResolveSharedIPs(cfg, st)

	var b strings.Builder
	b.WriteString("# qosnat2 — generated by qosnatd\n")
	b.WriteString("# mark 隔离: 禁止 meta mark set / flowtable；QoS 用 tc_classid，IFB 用 bpf_redirect\n")
	// 删除旧表在 Apply() 中按 TableExists() 执行，避免 ruleset 内 delete 导致 nft -c 失败（表未加载时）。
	b.WriteString(fmt.Sprintf("table inet %s {\n", TableName))
	writeAliasSets(&b, st.Firewall.Aliases)
	if st.Firewall.MaxSessionsPerIP > 0 {
		writeSessionLimitSet(&b)
	}

	// prerouting DNAT
	b.WriteString("    chain prerouting {\n")
	b.WriteString("        type nat hook prerouting priority dstnat; policy accept;\n")
	writeWanForwardRules(&b, cfg, st.Firewall.WanPortForwards)
	writeWanForwardHairpinRules(&b, cfg, st.Firewall.WanPortForwards)
	writeNPTv6Prerouting(&b, st.Nat)
	b.WriteString("    }\n\n")

	// postrouting SNAT
	b.WriteString("    chain postrouting {\n")
	b.WriteString("        type nat hook postrouting priority srcnat; policy accept;\n")
	writeNPTv6Postrouting(&b, cfg, st.Nat)
	if natOn {
		writeIPv4PostroutingNAT(&b, cfg, st, routes, ips, egress, st.Firewall.WanPortForwards)
	}
	b.WriteString("    }\n\n")

	// forward filter
	b.WriteString("    chain forward {\n")
	b.WriteString("        type filter hook forward priority filter; policy accept;\n")
	b.WriteString("        ct state established,related accept\n")
	writeSessionLimitRules(&b, st)
	writeFilterRules(&b, "forward", st.Firewall.FilterRules, st.Firewall.Schedules)
	egressDevs := make([]string, 0, len(egress))
	for _, e := range egress {
		if e.Device != "" {
			egressDevs = append(egressDevs, e.Device)
		}
	}
	wanForward := store.CollectWanForwardDevices(cfg.DevWAN, cfg.DevLAN, st, egressDevs)
	wanDevs := make(map[string]struct{}, len(wanForward))
	for _, dev := range wanForward {
		wanDevs[dev] = struct{}{}
	}
	if cfg.DevLAN != "" {
		for dev := range wanDevs {
			if dev == "" || dev == cfg.DevLAN {
				continue
			}
			b.WriteString(fmt.Sprintf("        iifname \"%s\" oifname \"%s\" accept\n", cfg.DevLAN, dev))
			b.WriteString(fmt.Sprintf("        iifname \"%s\" oifname \"%s\" accept\n", dev, cfg.DevLAN))
		}
		writeEgressSameIfaceForward(&b, cfg.DevLAN, egress)
		// 非对称回程：公网源直达 LAN 内网段丢弃（仅本机 SNAT 的策略网段；no_snat 由远端 NAT 回程）
		if natOn {
			allPolicyCIDRs := append(append([]string{}, routes...), snatEgressCIDRs...)
			for _, cidr := range allPolicyCIDRs {
				for dev := range wanDevs {
					if dev == "" || dev == cfg.DevLAN {
						continue
					}
					b.WriteString(fmt.Sprintf(
						"        iifname \"%s\" oifname \"%s\" ip daddr %s ip saddr != %s drop\n",
						dev, cfg.DevLAN, cidr, cidr,
					))
				}
			}
		}
	}
	// WARP netns veth（qwp0↔qwp1）；须在默认丢弃之前，否则 netns 无法经主 WAN 建连/注册。
	b.WriteString("        iifname \"qwp0\" accept comment \"qosnat2-forward-warp-netns\"\n")
	b.WriteString("        oifname \"qwp0\" accept comment \"qosnat2-forward-warp-netns\"\n")
	// ProxyEgress sing-box TUN（qpe*）；策略路由导向后需转发放行。
	b.WriteString("        iifname \"qpe*\" accept comment \"qosnat2-forward-proxy-egress\"\n")
	b.WriteString("        oifname \"qpe*\" accept comment \"qosnat2-forward-proxy-egress\"\n")
	// VPN 隧道转发（与 input 隧道放行一致；须在默认丢弃之前）
	b.WriteString("        iifname \"wg*\" accept comment \"qosnat2-forward-vpn-wg\"\n")
	b.WriteString("        oifname \"wg*\" accept comment \"qosnat2-forward-vpn-wg\"\n")
	b.WriteString("        iifname \"vpns*\" accept comment \"qosnat2-forward-vpn-ocserv\"\n")
	b.WriteString("        oifname \"vpns*\" accept comment \"qosnat2-forward-vpn-ocserv\"\n")
	// 除已建立连接、用户/自动规则、LAN↔WAN、VPN 隧道外，其余转发默认丢弃。
	b.WriteString("        drop comment \"qosnat2-forward-default-deny\"\n")
	b.WriteString("    }\n\n")

	// input（基础）
	b.WriteString("    chain input {\n")
	b.WriteString("        type filter hook input priority filter; policy accept;\n")
	b.WriteString("        iifname \"lo\" accept\n")
	b.WriteString("        ct state established,related accept\n")
	if st.System.AcmeTempAllowHTTP01 {
		// ACME http-01：须在 WAN 按口 drop 之前放行，且多 IP 时仅开放 DNS 解析到本机的目标地址。
		ips := st.System.AcmeTempAllowHTTP01IPs
		if len(ips) == 0 {
			b.WriteString("        tcp dport 80 accept comment \"qosnat2-acme-http01-open80\"\n")
		} else {
			for _, ip := range ips {
				ip = strings.TrimSpace(ip)
				if ip == "" {
					continue
				}
				b.WriteString(fmt.Sprintf("        ip daddr %s tcp dport 80 accept comment \"qosnat2-acme-http01\"\n", ip))
			}
		}
	}
	writeFilterRules(&b, "input", st.Firewall.FilterRules, st.Firewall.Schedules)
	if cfg.DevLAN != "" {
		b.WriteString(fmt.Sprintf("        iifname \"%s\" accept\n", cfg.DevLAN))
	}
	// IFB 上行整形（mirred 重定向）须放行入站，否则 u32/BPF 路径异常。
	b.WriteString("        iifname \"ifb0\" accept\n")
	// WARP netns veth 网关（198.18.0.0/30）；须在默认丢弃之前。
	b.WriteString("        iifname \"qwp0\" accept comment \"qosnat2-input-warp-netns\"\n")
	b.WriteString("        iifname \"qpe*\" accept comment \"qosnat2-input-proxy-egress\"\n")
	// VPN 隧道口：客户端访问隧道网关/DNS（控制面接入仍由 WAN auto 规则处理）。
	b.WriteString("        iifname \"wg*\" accept comment \"qosnat2-vpn-wg\"\n")
	b.WriteString("        iifname \"vpns*\" accept comment \"qosnat2-vpn-ocserv\"\n")
	// WAN 管理/VPN 放行 → 用户 input 规则 → WAN 按口丢弃：由 SyncAutoFilterRules 顺序写入 filter_rules。
	// 除 lo、LAN、ifb0 及已匹配的 WAN 放行项外，其余网卡入站一律丢弃。
	b.WriteString("        drop comment \"qosnat2-input-default-deny\"\n")
	b.WriteString("    }\n\n")

	// output：限制本机出站（用户规则 + 默认 accept，避免误断管理面）
	b.WriteString("    chain output {\n")
	b.WriteString("        type filter hook output priority filter; policy accept;\n")
	b.WriteString("        ct state established,related accept\n")
	writeFilterRules(&b, "output", st.Firewall.FilterRules, st.Firewall.Schedules)
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func writeIPv4PostroutingNAT(b *strings.Builder, cfg Config, st store.State, routes, ips []string, egress []store.ResolvedEgress, forwards []store.WanPortForward) {
	for _, inner := range sortedKeys(st.Nat.IPv4.StaticMappings) {
		b.WriteString(fmt.Sprintf("        ip saddr %s snat to %s\n", inner, st.Nat.IPv4.StaticMappings[inner]))
	}
	if len(st.Nat.IPv4.PrefixMappings) > 0 {
		b.WriteString(fmt.Sprintf("        oifname \"%s\" snat ip prefix to ip saddr map {\n", cfg.DevWAN))
		for _, inner := range sortedKeys(st.Nat.IPv4.PrefixMappings) {
			b.WriteString(fmt.Sprintf("            %s : %s,\n", inner, st.Nat.IPv4.PrefixMappings[inner]))
		}
		b.WriteString("        }\n")
	}
	for _, e := range egress {
		match := store.EgressSNATMatchClause(e.Policy)
		if match == "" {
			continue
		}
		if e.NoSNAT {
			// 跳出 postrouting，避免后续 catch-all masquerade 仍对本机做 SNAT。
			b.WriteString(fmt.Sprintf(
				"        %s return comment \"qosnat2-egress-no-snat\"\n",
				match,
			))
			continue
		}
		if e.Masquerade {
			b.WriteString(fmt.Sprintf(
				"        %s oifname \"%s\" masquerade\n",
				match, e.Device,
			))
			continue
		}
		b.WriteString(fmt.Sprintf(
			"        %s oifname \"%s\" snat to %s\n",
			match, e.Device, e.SNATIP,
		))
	}
	if len(ips) > 0 {
		var inline []string
		for i, ip := range ips {
			inline = append(inline, fmt.Sprintf("%d : %s", i, ip))
		}
		for _, cidr := range routes {
			b.WriteString(fmt.Sprintf(
				"        ip saddr %s oifname \"%s\" snat to numgen inc mod %d map { %s }\n",
				cidr, cfg.DevWAN, len(ips), strings.Join(inline, ", "),
			))
		}
	} else {
		for _, cidr := range routes {
			b.WriteString(fmt.Sprintf(
				"        ip saddr %s oifname \"%s\" masquerade\n",
				cidr, cfg.DevWAN,
			))
		}
	}
	writeWanForwardHairpinSNAT(b, cfg, forwards)
	b.WriteString(fmt.Sprintf("        oifname \"%s\" masquerade\n", cfg.DevWAN))
}

// writeEgressSameIfaceForward LAN 与 WanLink 同口时，转发路径为 iif=oif=LAN，需显式放行出站策略匹配流量。
func writeEgressSameIfaceForward(b *strings.Builder, devLAN string, egress []store.ResolvedEgress) {
	devLAN = strings.TrimSpace(devLAN)
	if devLAN == "" {
		return
	}
	for _, e := range egress {
		if e.Device != devLAN {
			continue
		}
		iif := devLAN
		if ifc := strings.TrimSpace(e.Policy.SrcIface); ifc != "" {
			iif = ifc
		}
		ipMatch := store.EgressSNATIPMatchClause(e.Policy)
		if ipMatch == "" && strings.TrimSpace(e.Policy.SrcIface) == "" {
			continue
		}
		b.WriteString(fmt.Sprintf(
			"        iifname \"%s\" oifname \"%s\" %s accept comment \"qosnat2-egress-same-iface\"\n",
			iif, e.Device, strings.TrimSpace(ipMatch),
		))
	}
}

// CheckRuleset 语法检查 ruleset（不写盘、不加载）。
func CheckRuleset(body string) error {
	f, err := os.CreateTemp("", "qosnat-nft-check-*.nft")
	if err != nil {
		return err
	}
	path := f.Name()
	defer os.Remove(path)
	if _, err := f.WriteString(body); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	out, err := exec.Command("nft", "-c", "-f", path).CombinedOutput()
	if err != nil {
		return fmt.Errorf("nft check: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// TableExists 报告 inet qosnat 表是否已加载。
func TableExists() bool {
	err := exec.Command("nft", "list", "table", "inet", TableName).Run()
	return err == nil
}

// deleteTableIfExists 删除 inet qosnat 表（不存在时静默成功）。
func deleteTableIfExists() error {
	if !TableExists() {
		return nil
	}
	out, err := exec.Command("nft", "delete", "table", "inet", TableName).CombinedOutput()
	if err != nil {
		return fmt.Errorf("nft delete table inet %s: %s %w", TableName, strings.TrimSpace(string(out)), err)
	}
	return nil
}

func dumpLiveTable() string {
	out, err := exec.Command("nft", "list", "table", "inet", TableName).CombinedOutput()
	if err != nil {
		return ""
	}
	s := strings.TrimSpace(string(out))
	if s == "" {
		return ""
	}
	return s + "\n"
}

func loadRulesetFile(path string) error {
	out, err := exec.Command("nft", "-f", path).CombinedOutput()
	if err != nil {
		return fmt.Errorf("nft load: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func restoreLiveTable(backup string) error {
	if strings.TrimSpace(backup) == "" {
		return fmt.Errorf("no backup ruleset")
	}
	f, err := os.CreateTemp("", "qosnat-nft-restore-*.nft")
	if err != nil {
		return err
	}
	path := f.Name()
	defer os.Remove(path)
	if _, err := f.WriteString(backup); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	if err := deleteTableIfExists(); err != nil {
		return err
	}
	return loadRulesetFile(path)
}

// Apply 生成、校验并加载 nftables；load 失败时尝试恢复先前 ruleset。
func Apply(cfg Config, st store.State) error {
	body, err := Render(cfg, st)
	if err != nil {
		return err
	}
	if err := CheckRuleset(body); err != nil {
		return err
	}
	liveBackup := dumpLiveTable()
	if liveBackup != "" {
		_ = os.WriteFile(RulesBackupPath, []byte(liveBackup), 0644)
	}
	if err := WriteRulesFile(body); err != nil {
		return err
	}
	if err := deleteTableIfExists(); err != nil {
		return err
	}
	if err := loadRulesetFile(RulesPath); err != nil {
		if liveBackup != "" {
			if revErr := restoreLiveTable(liveBackup); revErr != nil {
				return fmt.Errorf("%v; restore previous ruleset: %v", err, revErr)
			}
			return fmt.Errorf("%v (previous ruleset restored)", err)
		}
		return err
	}
	return nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// RemoveSharedIP 删除共享 IP
func RemoveSharedIP(st *store.State, ip string) bool {
	var out []string
	found := false
	for _, e := range st.Nat.IPv4.SharedIPs {
		if e == ip {
			found = true
			continue
		}
		out = append(out, e)
	}
	st.Nat.IPv4.SharedIPs = out
	return found
}

// AddSharedIP 追加共享 IP（API 用）
func AddSharedIP(st *store.State, ip string) error {
	if netParseIP(ip) != nil {
		return fmt.Errorf("invalid ip: %s", ip)
	}
	for _, e := range st.Nat.IPv4.SharedIPs {
		if e == ip {
			return nil
		}
	}
	st.Nat.IPv4.SharedIPs = append(st.Nat.IPv4.SharedIPs, ip)
	return nil
}

func netParseIP(s string) error {
	parts := strings.Split(s, ".")
	if len(parts) != 4 {
		return fmt.Errorf("bad ip")
	}
	for _, p := range parts {
		n, err := strconv.Atoi(p)
		if err != nil || n < 0 || n > 255 {
			return fmt.Errorf("bad ip")
		}
	}
	return nil
}
