package ocserv

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

func configPerGroupDir(o store.OCServState) string {
	d := strings.TrimSpace(o.ConfigPerGroup)
	if d == "" {
		d = strings.TrimSpace(o.Advanced.ConfigPerGroup)
	}
	if d == "" {
		d = "/etc/ocserv/config-per-group/"
	}
	if !strings.HasSuffix(d, "/") {
		d += "/"
	}
	return d
}

func renderGroupGlobals(b *bytes.Buffer, o store.OCServState) {
	// auth=radius 且 groupconfig=true 时本地组配置不生效：保留为注释，便于回切 plain 时恢复。
	commented := store.OCServRadiusUsesGroupconfig(o)
	prefix := ""
	if commented {
		prefix = "# "
	}
	if d := configPerGroupDir(o); d != "" {
		fmt.Fprintf(b, "%sconfig-per-group = %s\n", prefix, d)
	}
	if p := strings.TrimSpace(o.ConfigPerUser); p != "" {
		fmt.Fprintf(b, "%sconfig-per-user = %s\n", prefix, p)
	}
	if p := strings.TrimSpace(o.DefaultGroupConfig); p != "" {
		fmt.Fprintf(b, "%sdefault-group-config = %s\n", prefix, p)
	}
	if p := strings.TrimSpace(o.DefaultUserConfig); p != "" {
		fmt.Fprintf(b, "%sdefault-user-config = %s\n", prefix, p)
	}
	if o.AutoSelectGroup {
		fmt.Fprintf(b, "%sauto-select-group = true\n", prefix)
	} else if !commented {
		fmt.Fprintf(b, "%sauto-select-group = false\n", prefix)
	}
	if g := strings.TrimSpace(o.DefaultSelectGroup); g != "" {
		fmt.Fprintf(b, "%sdefault-select-group = %s\n", prefix, g)
	}
	for _, gr := range o.Groups {
		if gr.OmitSelectGroup {
			continue
		}
		line := gr.Name
		if lbl := strings.TrimSpace(gr.Label); lbl != "" {
			line = fmt.Sprintf("%s[%s]", gr.Name, lbl)
		}
		fmt.Fprintf(b, "%sselect-group = %s\n", prefix, line)
	}
}

func renderGroupConf(g store.OCServGroup) string {
	var b bytes.Buffer
	b.WriteString(fmt.Sprintf("# group %s — generated by qosnatd\n", g.Name))
	for _, d := range g.DNS {
		fmt.Fprintf(&b, "dns = %s\n", d)
	}
	for _, r := range g.Routes {
		fmt.Fprintf(&b, "route = %s\n", r)
	}
	for _, r := range g.NoRoutes {
		fmt.Fprintf(&b, "no-route = %s\n", r)
	}
	if n := strings.TrimSpace(g.IPv4Network); n != "" {
		fmt.Fprintf(&b, "ipv4-network = %s\n", n)
	}
	if m := strings.TrimSpace(g.IPv4Netmask); m != "" {
		fmt.Fprintf(&b, "ipv4-netmask = %s\n", m)
	}
	if g.RxDataPerSec > 0 {
		fmt.Fprintf(&b, "rx-data-per-sec = %d\n", g.RxDataPerSec)
	}
	if g.TxDataPerSec > 0 {
		fmt.Fprintf(&b, "tx-data-per-sec = %d\n", g.TxDataPerSec)
	}
	if g.MTU > 0 {
		fmt.Fprintf(&b, "mtu = %d\n", g.MTU)
	}
	if g.TunnelAllDNS {
		b.WriteString("tunnel-all-dns = true\n")
	}
	return b.String()
}

// WriteGroupConfigs 同步组配置目录与默认组配置（plain 或 radius 未启用 groupconfig 时）
func WriteGroupConfigs(o store.OCServState) error {
	if store.OCServRadiusUsesGroupconfig(o) {
		return nil
	}
	dir := configPerGroupDir(o)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(strings.TrimSpace(o.DefaultGroupConfig)), 0755); err != nil {
		return err
	}
	defPath := strings.TrimSpace(o.DefaultGroupConfig)
	if defPath == "" {
		defPath = "/etc/ocserv/defaults/group.conf"
	}
	if _, err := os.Stat(defPath); os.IsNotExist(err) {
		if err := os.WriteFile(defPath, []byte("# default group — qosnatd\n"), 0644); err != nil {
			return err
		}
	}
	// 清理已删除的组文件（ocserv 组配置不带 .conf 后缀；同时移除遗留 *.conf）
	entries, _ := os.ReadDir(dir)
	want := map[string]bool{}
	for _, g := range o.Groups {
		want[g.Name] = true
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		base := strings.TrimSuffix(name, ".conf")
		if want[name] || want[base] {
			continue
		}
		if !strings.Contains(name, ".") || strings.HasSuffix(name, ".conf") {
			_ = os.Remove(filepath.Join(dir, name))
		}
	}
	for _, g := range o.Groups {
		p := filepath.Join(dir, g.Name)
		if err := os.WriteFile(p, []byte(renderGroupConf(g)), 0644); err != nil {
			return fmt.Errorf("write group %s: %w", g.Name, err)
		}
		legacy := filepath.Join(dir, g.Name+".conf")
		if _, err := os.Stat(legacy); err == nil {
			_ = os.Remove(legacy)
		}
	}
	return nil
}

func renderVhosts(b *bytes.Buffer, o store.OCServState, managed []store.ManagedCertificate) {
	for _, v := range o.Vhosts {
		if !v.Enabled {
			continue
		}
		renderVhostBlock(b, v, o, managed)
	}
}
