package ocserv

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

func configPerGroupDir(o store.OCServState) string {
	d := strings.TrimSpace(o.ConfigPerGroup)
	if d == "" {
		d = strings.TrimSpace(o.Advanced.ConfigPerGroup)
	}
	if d == "" {
		d = "/etc/ocserv/config-per-group/"
	}
	if !strings.HasSuffix(d, "/") {
		d += "/"
	}
	return d
}

func renderGroupGlobals(b *bytes.Buffer, o store.OCServState) {
	if d := configPerGroupDir(o); d != "" {
		fmt.Fprintf(b, "config-per-group = %s\n", d)
	}
	if p := strings.TrimSpace(o.ConfigPerUser); p != "" {
		fmt.Fprintf(b, "config-per-user = %s\n", p)
	}
	if p := strings.TrimSpace(o.DefaultGroupConfig); p != "" {
		fmt.Fprintf(b, "default-group-config = %s\n", p)
	}
	if p := strings.TrimSpace(o.DefaultUserConfig); p != "" {
		fmt.Fprintf(b, "default-user-config = %s\n", p)
	}
	if o.AutoSelectGroup {
		b.WriteString("auto-select-group = true\n")
	}
	if g := strings.TrimSpace(o.DefaultSelectGroup); g != "" {
		fmt.Fprintf(b, "default-select-group = %s\n", g)
	}
	for _, gr := range o.Groups {
		line := gr.Name
		if lbl := strings.TrimSpace(gr.Label); lbl != "" {
			line = fmt.Sprintf("%s[%s]", gr.Name, lbl)
		}
		fmt.Fprintf(b, "select-group = %s\n", line)
	}
}

func renderGroupConf(g store.OCServGroup) string {
	var b bytes.Buffer
	b.WriteString(fmt.Sprintf("# group %s — generated by qosnatd\n", g.Name))
	for _, d := range g.DNS {
		fmt.Fprintf(&b, "dns = %s\n", d)
	}
	for _, r := range g.Routes {
		fmt.Fprintf(&b, "route = %s\n", r)
	}
	for _, r := range g.NoRoutes {
		fmt.Fprintf(&b, "no-route = %s\n", r)
	}
	if n := strings.TrimSpace(g.IPv4Network); n != "" {
		fmt.Fprintf(&b, "ipv4-network = %s\n", n)
	}
	if m := strings.TrimSpace(g.IPv4Netmask); m != "" {
		fmt.Fprintf(&b, "ipv4-netmask = %s\n", m)
	}
	if g.RxDataPerSec > 0 {
		fmt.Fprintf(&b, "rx-data-per-sec = %d\n", g.RxDataPerSec)
	}
	if g.TxDataPerSec > 0 {
		fmt.Fprintf(&b, "tx-data-per-sec = %d\n", g.TxDataPerSec)
	}
	if g.MTU > 0 {
		fmt.Fprintf(&b, "mtu = %d\n", g.MTU)
	}
	if g.TunnelAllDNS {
		b.WriteString("tunnel-all-dns = true\n")
	}
	return b.String()
}

// WriteGroupConfigs 同步组配置目录与默认组配置
func WriteGroupConfigs(o store.OCServState) error {
	dir := configPerGroupDir(o)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(strings.TrimSpace(o.DefaultGroupConfig)), 0755); err != nil {
		return err
	}
	defPath := strings.TrimSpace(o.DefaultGroupConfig)
	if defPath == "" {
		defPath = "/etc/ocserv/defaults/group.conf"
	}
	if _, err := os.Stat(defPath); os.IsNotExist(err) {
		if err := os.WriteFile(defPath, []byte("# default group — qosnatd\n"), 0644); err != nil {
			return err
		}
	}
	// 清理已删除的组文件：仅删除我们曾管理的名称为 *.conf
	entries, _ := os.ReadDir(dir)
	want := map[string]bool{}
	for _, g := range o.Groups {
		want[g.Name+".conf"] = true
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(name, ".conf") && !want[name] {
			_ = os.Remove(filepath.Join(dir, name))
		}
	}
	for _, g := range o.Groups {
		p := filepath.Join(dir, g.Name+".conf")
		if err := os.WriteFile(p, []byte(renderGroupConf(g)), 0644); err != nil {
			return fmt.Errorf("write group %s: %w", g.Name, err)
		}
	}
	return nil
}

func renderVhosts(b *bytes.Buffer, o store.OCServState) {
	for _, v := range o.Vhosts {
		if !v.Enabled {
			continue
		}
		domain := strings.TrimSpace(v.Domain)
		if domain == "" {
			continue
		}
		fmt.Fprintf(b, "\n[vhost:%s]\n", domain)
		switch strings.TrimSpace(v.AuthMethod) {
		case store.OCServAuthPlain:
			fmt.Fprintf(b, "auth = \"plain[passwd=%s]\"\n", PasswdPath)
		case store.OCServAuthRadius:
			b.WriteString(radiusAuthDirective(o))
		case "certificate":
			b.WriteString("auth = \"certificate\"\n")
		}
		cert, key, ca := resolveCertPaths(o)
		if p := strings.TrimSpace(v.ServerCertPath); p != "" {
			cert = p
		}
		if p := strings.TrimSpace(v.ServerKeyPath); p != "" {
			key = p
		}
		if p := strings.TrimSpace(v.CaCertPath); p != "" {
			ca = p
		}
		if cert != "" {
			fmt.Fprintf(b, "server-cert = %s\n", cert)
		}
		if key != "" {
			fmt.Fprintf(b, "server-key = %s\n", key)
		}
		if ca != "" {
			fmt.Fprintf(b, "ca-cert = %s\n", ca)
		}
		if n := strings.TrimSpace(v.IPv4Network); n != "" {
			fmt.Fprintf(b, "ipv4-network = %s\n", n)
		}
		if m := strings.TrimSpace(v.IPv4Netmask); m != "" {
			fmt.Fprintf(b, "ipv4-netmask = %s\n", m)
		}
		for _, d := range v.DNS {
			fmt.Fprintf(b, "dns = %s\n", d)
		}
		for _, r := range v.Routes {
			fmt.Fprintf(b, "route = %s\n", r)
		}
		if oid := strings.TrimSpace(v.CertUserOID); oid != "" {
			fmt.Fprintf(b, "cert-user-oid = %s\n", oid)
		}
	}
}
