package ocserv

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	SysconfDir     = "/etc/ocserv"
	ConfPath       = SysconfDir + "/ocserv.conf"
	PasswdPath     = SysconfDir + "/ocpasswd"
	DefaultCert    = SysconfDir + "/server-cert.pem"
	DefaultKey     = SysconfDir + "/server-key.pem"
	QoSnatTLSCert  = "/etc/qosnat2/tls.crt"
	QoSnatTLSKey   = "/etc/qosnat2/tls.key"
	BinaryPath     = "/usr/local/sbin/ocserv"
	OcpasswdPath   = "/usr/local/sbin/ocpasswd"
)

// Status 运行状态
type Status struct {
	Installed    bool   `json:"installed"`
	Active       bool   `json:"active"`
	Version      string `json:"version,omitempty"`
	Binary       string `json:"binary,omitempty"`
	RadiusLinked bool   `json:"radius_linked"`
}

// InstallInfo 是否已从源码安装
func InstallInfo() Status {
	st := Status{Binary: BinaryPath}
	if p, err := exec.LookPath("ocserv"); err == nil {
		st.Installed = true
		st.Binary = p
		out, _ := exec.Command(p, "--version").CombinedOutput()
		st.Version = strings.TrimSpace(string(out))
	} else if _, err := os.Stat(BinaryPath); err == nil {
		st.Installed = true
		out, _ := exec.Command(BinaryPath, "--version").CombinedOutput()
		st.Version = strings.TrimSpace(string(out))
	}
	if st.Installed {
		out, _ := exec.Command("systemctl", "is-active", "ocserv").Output()
		st.Active = strings.TrimSpace(string(out)) == "active"
		st.RadiusLinked = RadiusLinked()
	}
	return st
}

// RenderConf 生成 ocserv.conf
func RenderConf(o store.OCServState) string {
	cert, key := o.ServerCert, o.ServerKey
	if o.UseQoSnatTLS || cert == "" {
		cert = DefaultCert
		key = DefaultKey
	}
	var b bytes.Buffer
	b.WriteString("# Generated by qosnatd — do not edit manually; use Web UI\n")
	if store.OCServUsesRadius(o) {
		b.WriteString(radiusAuthDirective(o))
		b.WriteString("\n")
		for _, line := range radiusAcctLines(o) {
			b.WriteString(line)
			b.WriteString("\n")
		}
	} else {
		b.WriteString(fmt.Sprintf("auth = \"plain[passwd=%s]\"\n", PasswdPath))
	}
	b.WriteString("run-as-user = nobody\n")
	b.WriteString("run-as-group = daemon\n")
	b.WriteString("socket-file = /var/run/ocserv.sock\n")
	b.WriteString(fmt.Sprintf("server-cert = %s\n", cert))
	b.WriteString(fmt.Sprintf("server-key = %s\n", key))
	b.WriteString(fmt.Sprintf("ipv4-network = %s\n", o.IPv4Network))
	b.WriteString(fmt.Sprintf("ipv4-netmask = %s\n", o.IPv4Netmask))
	for _, d := range o.DNS {
		b.WriteString(fmt.Sprintf("dns = %s\n", strings.TrimSpace(d)))
	}
	for _, r := range o.Routes {
		b.WriteString(fmt.Sprintf("route = %s\n", strings.TrimSpace(r)))
	}
	b.WriteString(fmt.Sprintf("device = %s\n", o.Device))
	b.WriteString(fmt.Sprintf("max-clients = %d\n", o.MaxClients))
	renderAdvanced(&b, o)
	return b.String()
}

// WriteConf 写 ocserv.conf 并同步证书
func WriteConf(o store.OCServState) error {
	if err := os.MkdirAll(SysconfDir, 0755); err != nil {
		return err
	}
	if o.UseQoSnatTLS {
		if err := syncCertsFromQoSnat(); err != nil {
			return err
		}
	} else if o.ServerCert != "" && o.ServerKey != "" {
		if err := os.WriteFile(DefaultCert, []byte(o.ServerCert), 0644); err != nil {
			return err
		}
		if err := os.WriteFile(DefaultKey, []byte(o.ServerKey), 0600); err != nil {
			return err
		}
	}
	if store.OCServUsesRadius(o) {
		if err := WriteRadcliConfig(o); err != nil {
			return err
		}
		if !RadiusLinked() {
			return fmt.Errorf("ocserv 未编译 RADIUS 支持，请重装: sudo %s（需 libradcli-dev）", InstallScriptPath())
		}
	} else if err := SyncUsers(o.Users); err != nil {
		return err
	}
	return os.WriteFile(ConfPath, []byte(RenderConf(o)), 0644)
}

func syncCertsFromQoSnat() error {
	if _, err := os.Stat(QoSnatTLSCert); err != nil {
		return fmt.Errorf("qosnat TLS cert missing: %w", err)
	}
	if _, err := os.Stat(QoSnatTLSKey); err != nil {
		return fmt.Errorf("qosnat TLS key missing: %w", err)
	}
	in, err := os.ReadFile(QoSnatTLSCert)
	if err != nil {
		return err
	}
	if err := os.WriteFile(DefaultCert, in, 0644); err != nil {
		return err
	}
	in, err = os.ReadFile(QoSnatTLSKey)
	if err != nil {
		return err
	}
	return os.WriteFile(DefaultKey, in, 0600)
}

// SyncUsers 重建 ocpasswd（plain 用户）
func SyncUsers(users []store.OCServUser) error {
	ocpasswd := OcpasswdPath
	if p, err := exec.LookPath("ocpasswd"); err == nil {
		ocpasswd = p
	}
	_ = os.Remove(PasswdPath)
	for _, u := range users {
		if u.Username == "" || u.Password == "" {
			continue
		}
		cmd := exec.Command(ocpasswd, "-c", PasswdPath, u.Username)
		cmd.Stdin = strings.NewReader(u.Password + "\n")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("ocpasswd %s: %s %w", u.Username, strings.TrimSpace(string(out)), err)
		}
	}
	if _, err := os.Stat(PasswdPath); os.IsNotExist(err) {
		return os.WriteFile(PasswdPath, []byte{}, 0600)
	}
	return os.Chmod(PasswdPath, 0600)
}

// Apply 写配置并 systemctl restart|stop ocserv
func Apply(o store.OCServState, up bool) error {
	st := InstallInfo()
	if !st.Installed {
		return fmt.Errorf("ocserv not installed; run: sudo /opt/qosnat2/scripts/install-ocserv.sh")
	}
	if err := WriteConf(o); err != nil {
		return err
	}
	if up {
		out, err := exec.Command("systemctl", "enable", "ocserv").CombinedOutput()
		if err != nil {
			return fmt.Errorf("systemctl enable: %s %w", strings.TrimSpace(string(out)), err)
		}
		out, err = exec.Command("systemctl", "restart", "ocserv").CombinedOutput()
		if err != nil {
			return fmt.Errorf("systemctl restart: %s %w", strings.TrimSpace(string(out)), err)
		}
		return nil
	}
	out, err := exec.Command("systemctl", "stop", "ocserv").CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl stop: %s %w", strings.TrimSpace(string(out)), err)
	}
	_, _ = exec.Command("systemctl", "disable", "ocserv").CombinedOutput()
	return nil
}

// InstallScriptPath 返回仓库内安装脚本路径
func InstallScriptPath() string {
	for _, p := range []string{
		"/opt/qosnat2/scripts/install-ocserv.sh",
		filepath.Join(filepath.Dir(os.Args[0]), "../scripts/install-ocserv.sh"),
	} {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return "/opt/qosnat2/scripts/install-ocserv.sh"
}
