package ocserv

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	SysconfDir    = "/etc/ocserv"
	ConfPath      = SysconfDir + "/ocserv.conf"
	PasswdPath    = SysconfDir + "/ocpasswd"
	DefaultCert   = SysconfDir + "/certs/server-cert.pem"
	DefaultKey    = SysconfDir + "/certs/server-key.pem"
	QoSnatTLSCert = "/etc/qosnat2/tls.crt"
	QoSnatTLSKey  = "/etc/qosnat2/tls.key"
	BinaryPath    = "/usr/local/sbin/ocserv"
	OcpasswdPath  = "/usr/local/bin/ocpasswd"
)

// Status 运行状态
type Status struct {
	Installed    bool   `json:"installed"`
	Active       bool   `json:"active"`
	Version      string `json:"version,omitempty"`
	Binary       string `json:"binary,omitempty"`
	RadiusLinked bool   `json:"radius_linked"`
}

// InstallInfo 是否已从源码安装
func InstallInfo() Status {
	st := Status{Binary: BinaryPath}
	if p, err := exec.LookPath("ocserv"); err == nil {
		st.Installed = true
		st.Binary = p
		out, _ := exec.Command(p, "--version").CombinedOutput()
		st.Version = strings.TrimSpace(string(out))
	} else if _, err := os.Stat(BinaryPath); err == nil {
		st.Installed = true
		out, _ := exec.Command(BinaryPath, "--version").CombinedOutput()
		st.Version = strings.TrimSpace(string(out))
	}
	if st.Installed {
		out, _ := exec.Command("systemctl", "is-active", "ocserv").Output()
		st.Active = strings.TrimSpace(string(out)) == "active"
		st.RadiusLinked = RadiusLinked()
	}
	return st
}

func defaultCertDestPaths(o store.OCServState) (cert, key string) {
	cert = strings.TrimSpace(o.ServerCertPath)
	key = strings.TrimSpace(o.ServerKeyPath)
	if cert == "" {
		cert = DefaultCert
	}
	if key == "" {
		key = DefaultKey
	}
	return cert, key
}

// RenderConf 生成 ocserv.conf
func RenderConf(o store.OCServState, managed []store.ManagedCertificate) string {
	cert, key, ca := store.ResolveOCServGlobalCerts(o, managed)
	sock := strings.TrimSpace(o.SocketFile)
	if sock == "" {
		sock = "/var/run/ocserv-socket"
	}
	var b bytes.Buffer
	b.WriteString("# Generated by qosnatd — do not edit manually; use Web UI\n")
	if store.OCServUsesRadius(o) {
		b.WriteString(radiusAuthDirective(o))
		b.WriteString("\n")
		for _, line := range radiusAcctLines(o) {
			b.WriteString(line)
			b.WriteString("\n")
		}
	} else {
		b.WriteString(fmt.Sprintf("auth = \"plain[passwd=%s]\"\n", PasswdPath))
	}
	b.WriteString("run-as-user = nobody\n")
	b.WriteString("run-as-group = daemon\n")
	b.WriteString(fmt.Sprintf("socket-file = %s\n", sock))
	b.WriteString(fmt.Sprintf("server-cert = %s\n", cert))
	b.WriteString(fmt.Sprintf("server-key = %s\n", key))
	if ca != "" {
		b.WriteString(fmt.Sprintf("ca-cert = %s\n", ca))
	}
	b.WriteString(fmt.Sprintf("ipv4-network = %s\n", o.IPv4Network))
	b.WriteString(fmt.Sprintf("ipv4-netmask = %s\n", o.IPv4Netmask))
	for _, d := range o.DNS {
		b.WriteString(fmt.Sprintf("dns = %s\n", strings.TrimSpace(d)))
	}
	for _, r := range o.Routes {
		b.WriteString(fmt.Sprintf("route = %s\n", strings.TrimSpace(r)))
	}
	for _, r := range o.NoRoutes {
		b.WriteString(fmt.Sprintf("no-route = %s\n", strings.TrimSpace(r)))
	}
	b.WriteString(fmt.Sprintf("device = %s\n", o.Device))
	b.WriteString(fmt.Sprintf("max-clients = %d\n", o.MaxClients))
	renderGroupGlobals(&b, o)
	renderAdvanced(&b, o)
	renderVhosts(&b, o, managed)
	return b.String()
}

// WriteConf 写 ocserv.conf 并同步证书
func WriteConf(o store.OCServState, managed []store.ManagedCertificate) error {
	if err := os.MkdirAll(SysconfDir, 0755); err != nil {
		return err
	}
	destCert, destKey := defaultCertDestPaths(o)
	if strings.TrimSpace(o.ManagedCertID) == "" && o.UseQoSnatTLS {
		if err := syncCertsToPaths(destCert, destKey); err != nil {
			return err
		}
	} else if o.ServerCert != "" && o.ServerKey != "" {
		if err := writePEMFiles(destCert, destKey, o.ServerCert, o.ServerKey); err != nil {
			return err
		}
	}
	if store.OCServUsesRadius(o) {
		o2 := o
		if err := NormalizeRadiusConfig(&o2); err != nil {
			return err
		}
		if err := WriteRadcliConfig(o2); err != nil {
			return err
		}
		if !RadiusLinked() {
			return fmt.Errorf("ocserv 未编译 RADIUS 支持，请重装: sudo %s（需 libradcli-dev）", InstallScriptPath())
		}
	}
	if err := SyncVhostRadcliConfigs(o.Vhosts); err != nil {
		return err
	}
	if !store.OCServUsesRadius(o) {
		if err := SyncUsers(o.Users); err != nil {
			return err
		}
	}
	if err := WriteGroupConfigs(o); err != nil {
		return err
	}
	return os.WriteFile(ConfPath, []byte(RenderConf(o, managed)), 0644)
}

func syncCertsToPaths(certPath, keyPath string) error {
	if _, err := os.Stat(QoSnatTLSCert); err != nil {
		return fmt.Errorf("qosnat TLS cert missing: %w", err)
	}
	if _, err := os.Stat(QoSnatTLSKey); err != nil {
		return fmt.Errorf("qosnat TLS key missing: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(certPath), 0755); err != nil {
		return err
	}
	in, err := os.ReadFile(QoSnatTLSCert)
	if err != nil {
		return err
	}
	if err := os.WriteFile(certPath, in, 0644); err != nil {
		return err
	}
	in, err = os.ReadFile(QoSnatTLSKey)
	if err != nil {
		return err
	}
	return os.WriteFile(keyPath, in, 0600)
}

func writePEMFiles(certPath, keyPath, certPEM, keyPEM string) error {
	if err := os.MkdirAll(filepath.Dir(certPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(certPath, []byte(certPEM), 0644); err != nil {
		return err
	}
	return os.WriteFile(keyPath, []byte(keyPEM), 0600)
}

// SyncUsers 重建默认 ocpasswd（plain 用户）
func SyncUsers(users []store.OCServUser) error {
	return SyncUsersToPath(PasswdPath, users)
}

// SyncUsersToPath 重建指定路径的 ocpasswd 文件
func SyncUsersToPath(passwdPath string, users []store.OCServUser) error {
	passwdPath = strings.TrimSpace(passwdPath)
	if passwdPath == "" {
		return fmt.Errorf("passwd path required")
	}
	ocpasswd := OcpasswdPath
	if p, err := exec.LookPath("ocpasswd"); err == nil {
		ocpasswd = p
	}
	if err := os.MkdirAll(filepath.Dir(passwdPath), 0755); err != nil {
		return err
	}
	_ = os.Remove(passwdPath)
	for _, u := range users {
		if u.Username == "" || u.Password == "" {
			continue
		}
		args := []string{"-c", passwdPath}
		if g := strings.TrimSpace(u.Group); g != "" {
			args = append(args, "-g", g)
		}
		args = append(args, u.Username)
		cmd := exec.Command(ocpasswd, args...)
		cmd.Stdin = strings.NewReader(u.Password + "\n")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("ocpasswd %s: %s %w", u.Username, strings.TrimSpace(string(out)), err)
		}
	}
	if _, err := os.Stat(passwdPath); os.IsNotExist(err) {
		if err := os.WriteFile(passwdPath, []byte{}, 0600); err != nil {
			return err
		}
	}
	return os.Chmod(passwdPath, 0600)
}

// VhostEffectiveAuth 返回 vhost 实际认证方式（空则继承全局）
func VhostEffectiveAuth(v store.OCServVhost, globalAuth string) string {
	if a := strings.TrimSpace(v.AuthMethod); a != "" {
		return a
	}
	return strings.TrimSpace(globalAuth)
}

// VhostCanManagePlainUsers 是否可在 vhost 页管理独立密码文件用户
func VhostCanManagePlainUsers(v store.OCServVhost, globalAuth string) bool {
	if VhostEffectiveAuth(v, globalAuth) != store.OCServAuthPlain {
		return false
	}
	return strings.TrimSpace(v.PlainPasswdPath) != ""
}

// Reload 向运行中的 ocserv 发送 reload（不中断已有 VPN 连接）
func Reload(o store.OCServState) error {
	cfg := OcctlFromState(o)
	cmdArgs := append([]string{}, cfg.occtlSocketArg()...)
	cmdArgs = append(cmdArgs, "reload")
	cmd := exec.Command(occtlBin(), cmdArgs...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("occtl reload: %s %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// SyncPlainUsers 将 store 中本地用户写入 ocpasswd（plain 认证）
func SyncPlainUsers(o store.OCServState) error {
	if store.OCServUsesRadius(o) {
		return nil
	}
	return SyncUsers(o.Users)
}

// Apply 写入 ocserv.conf。运行中仅执行 reload（SIGHUP / systemctl reload），不再自动 restart；
// 对 ocserv(8) 中标记为不可 reload 生效的项，须由用户手动「重启 ocserv」后进程才会加载。
// 返回值 applyMode：reload | start | stop
func Apply(o store.OCServState, managed []store.ManagedCertificate, up bool) (applyMode string, err error) {
	st := InstallInfo()
	if !st.Installed {
		return "", fmt.Errorf("ocserv not installed; run: sudo /opt/qosnat2/scripts/install-ocserv.sh")
	}
	if err := ValidateState(o); err != nil {
		return "", err
	}
	if err := WriteConf(o, managed); err != nil {
		return "", err
	}
	if err := EnsureSystemdUnit(); err != nil {
		return "", err
	}
	var out []byte
	if up {
		out, err = exec.Command("systemctl", "enable", "ocserv").CombinedOutput()
		if err != nil {
			return "", fmt.Errorf("systemctl enable: %s %w", strings.TrimSpace(string(out)), err)
		}
		if st.Active {
			out, err = exec.Command("systemctl", "reload", "ocserv").CombinedOutput()
			if err != nil {
				if err2 := Reload(o); err2 != nil {
					return "", fmt.Errorf("ocserv reload failed (systemctl: %s): %w", strings.TrimSpace(string(out)), err2)
				}
			}
			return "reload", nil
		}
		out, err = exec.Command("systemctl", "start", "ocserv").CombinedOutput()
		if err != nil {
			return "", fmt.Errorf("systemctl start: %s %w", strings.TrimSpace(string(out)), err)
		}
		return "start", nil
	}
	out, err = exec.Command("systemctl", "stop", "ocserv").CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("systemctl stop: %s %w", strings.TrimSpace(string(out)), err)
	}
	_, _ = exec.Command("systemctl", "disable", "ocserv").CombinedOutput()
	return "stop", nil
}

// ServiceControl 执行 systemctl start|stop|restart（需 root）。
func ServiceControl(action string) error {
	action = strings.TrimSpace(strings.ToLower(action))
	switch action {
	case "start", "stop", "restart":
	default:
		return fmt.Errorf("invalid service action %q", action)
	}
	st := InstallInfo()
	if !st.Installed {
		return fmt.Errorf("ocserv not installed")
	}
	if err := EnsureSystemdUnit(); err != nil {
		return err
	}
	if action == "start" {
		out, err := exec.Command("systemctl", "enable", "ocserv").CombinedOutput()
		if err != nil {
			return fmt.Errorf("systemctl enable: %s %w", strings.TrimSpace(string(out)), err)
		}
	}
	out, err := exec.Command("systemctl", action, "ocserv").CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %s: %s %w", action, strings.TrimSpace(string(out)), err)
	}
	return nil
}

// InstallScriptPath 返回仓库内安装脚本路径
func InstallScriptPath() string {
	for _, p := range []string{
		"/opt/qosnat2/scripts/install-ocserv.sh",
		filepath.Join(filepath.Dir(os.Args[0]), "../scripts/install-ocserv.sh"),
	} {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return "/opt/qosnat2/scripts/install-ocserv.sh"
}
