package ocserv

import (
	_ "embed"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

//go:embed data/radcli-dictionary.txt
var radcliDictionary string

const (
	RadcliDir            = "/etc/radcli"
	RadiusClientConfPath = RadcliDir + "/radiusclient.conf"
	RadcliServersPath    = RadcliDir + "/servers"
	RadcliDictionaryPath = RadcliDir + "/dictionary"
)

func radiusConfigPath(o store.OCServState) string {
	if p := strings.TrimSpace(o.Radius.ConfigPath); p != "" {
		return p
	}
	return RadiusClientConfPath
}

// PrepareAndWriteRadcli normalizes radius.server (host-only in servers file) and writes /etc/radcli/*.
func PrepareAndWriteRadcli(o *store.OCServState) error {
	if err := NormalizeRadiusConfig(o); err != nil {
		return err
	}
	return WriteRadcliConfig(*o)
}

// WriteRadcliConfig writes /etc/radcli/* for ocserv radius auth.
// Caller should pass a host without ":port" in Radius.Server; use PrepareAndWriteRadcli when unsure.
func WriteRadcliConfig(o store.OCServState) error {
	if !store.OCServUsesRadius(o) {
		return nil
	}
	r := o.Radius
	host, portFromHost, err := parseRadiusServerHost(r.Server)
	if err != nil {
		return err
	}
	if host == "" {
		return fmt.Errorf("radius server required")
	}
	secret := strings.TrimSpace(r.Secret)
	if secret == "" {
		return fmt.Errorf("radius secret required")
	}
	authPort := r.AuthPort
	if authPort <= 0 {
		authPort = 1812
	}
	if portFromHost > 0 {
		authPort = portFromHost
	}
	acctPort := r.AcctPort
	if acctPort <= 0 {
		acctPort = 1813
	}
	confPath := RadiusClientConfPath
	serversPath := RadcliServersPath
	if p := strings.TrimSpace(r.ConfigPath); p != "" {
		confPath = p
		serversPath = strings.TrimSuffix(confPath, ".conf") + ".servers"
	}
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(RadcliDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(RadcliDictionaryPath, []byte(radcliDictionary), 0644); err != nil {
		return err
	}
	authAddr := formatRadiusHostPort(host, authPort)
	acctAddr := formatRadiusHostPort(host, acctPort)
	// radcli matches servers file by host/IP only (see rc_find_server); port comes from authserver line.
	servers := fmt.Sprintf("%s\t%s\t3\n", host, secret)
	if err := os.WriteFile(serversPath, []byte(servers), 0600); err != nil {
		return err
	}
	conf := fmt.Sprintf(`# Generated by qosnatd — do not edit manually; use Web UI
authserver %s
acctserver %s
servers %s
dictionary %s
bindaddr *
radius_timeout 10
radius_retries 3
`, authAddr, acctAddr, serversPath, RadcliDictionaryPath)
	if err := os.WriteFile(confPath, []byte(conf), 0644); err != nil {
		return err
	}
	return nil
}

// NormalizeRadiusConfig strips an optional :port from the server field into auth_port.
func NormalizeRadiusConfig(o *store.OCServState) error {
	if !store.OCServUsesRadius(*o) {
		return nil
	}
	host, port, err := parseRadiusServerHost(o.Radius.Server)
	if err != nil {
		return err
	}
	o.Radius.Server = host
	if port > 0 && (o.Radius.AuthPort <= 0 || o.Radius.AuthPort == 1812) {
		o.Radius.AuthPort = port
	}
	return nil
}

// parseRadiusServerHost returns host for /etc/radcli/servers (no port). Optional :port in UI is stripped
// and may override auth port when auth_port is unset/default.
func parseRadiusServerHost(raw string) (host string, port int, err error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", 0, nil
	}
	if h, p, e := net.SplitHostPort(raw); e == nil {
		host = strings.TrimSpace(h)
		port, err = strconv.Atoi(p)
		if err != nil || port <= 0 || port > 65535 {
			return "", 0, fmt.Errorf("invalid radius server port in %q", raw)
		}
		return host, port, nil
	}
	// Bracketed IPv6 without port, or plain hostname/IP.
	if strings.HasPrefix(raw, "[") && strings.HasSuffix(raw, "]") {
		return raw[1 : len(raw)-1], 0, nil
	}
	return raw, 0, nil
}

func formatRadiusHostPort(host string, port int) string {
	host = strings.TrimSpace(host)
	if strings.HasPrefix(host, "[") {
		return fmt.Sprintf("%s:%d", host, port)
	}
	if strings.Contains(host, ":") && !strings.Contains(host, ".") {
		return fmt.Sprintf("[%s]:%d", host, port)
	}
	return fmt.Sprintf("%s:%d", host, port)
}

func radiusAuthDirective(o store.OCServState) string {
	cfg := radiusConfigPath(o)
	opts := []string{"config=" + cfg}
	if o.Radius.GroupConfig {
		opts = append(opts, "groupconfig=true")
	}
	if nas := strings.TrimSpace(o.Radius.NASIdentifier); nas != "" {
		opts = append(opts, "nas-identifier="+nas)
	}
	return fmt.Sprintf(`auth = "radius[%s]"`, strings.Join(opts, ","))
}

func radiusAcctLines(o store.OCServState) []string {
	if !o.Radius.AcctEnabled {
		return nil
	}
	cfg := radiusConfigPath(o)
	interval := o.Radius.StatsReportTime
	if interval <= 0 {
		interval = 360
	}
	return []string{
		fmt.Sprintf(`acct = "radius[config=%s]"`, cfg),
		fmt.Sprintf("stats-report-time = %d", interval),
	}
}

// RadiusLinked reports whether ocserv was built with radcli/radiusclient.
func RadiusLinked() bool {
	bin := BinaryPath
	if p, err := exec.LookPath("ocserv"); err == nil {
		bin = p
	} else if _, err := os.Stat(BinaryPath); err != nil {
		return false
	}
	out, err := exec.Command("ldd", bin).CombinedOutput()
	if err != nil {
		return false
	}
	s := string(out)
	return strings.Contains(s, "radcli") || strings.Contains(s, "radiusclient")
}
