package ocserv

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/hk59775634/qosnat2/internal/store"
)

const (
	RadcliDir            = "/etc/radcli"
	RadiusClientConfPath = RadcliDir + "/radiusclient.conf"
	RadcliServersPath    = RadcliDir + "/servers"
	RadcliDictionaryPath = RadcliDir + "/dictionary"
)

// minimal dictionary for ocserv (see ocserv doc/README-radius.md)
const radcliDictionary = `# Generated by qosnatd — ocserv RADIUS attributes
ATTRIBUTE	User-Name		1	string
ATTRIBUTE	Password		2	string
ATTRIBUTE	NAS-Port		5	integer
ATTRIBUTE	Framed-Protocol		7	integer
ATTRIBUTE	NAS-Identifier		32	string
ATTRIBUTE	Acct-Input-Octets	42	integer
ATTRIBUTE	Acct-Output-Octets	43	integer
ATTRIBUTE	Acct-Session-Id		44	string
ATTRIBUTE	Acct-Input-Gigawords	52	integer
ATTRIBUTE	Acct-Output-Gigawords	53	integer
ATTRIBUTE	Acct-Interim-Interval	85	integer
ATTRIBUTE	Connect-Info		77	string
ATTRIBUTE	NAS-IP-Address		4	ipaddr
ATTRIBUTE	Framed-IP-Address	8	ipaddr
ATTRIBUTE	Framed-IP-Netmask	9	ipaddr
ATTRIBUTE	Framed-Route		22	string
ATTRIBUTE	Class			25	string
VENDOR Microsoft 311
BEGIN-VENDOR Microsoft
ATTRIBUTE	MS-Primary-DNS-Server	28	ipaddr
ATTRIBUTE	MS-Secondary-DNS-Server	29	ipaddr
END-VENDOR Microsoft
ATTRIBUTE	NAS-IPv6-Address		95	string
ATTRIBUTE	Delegated-IPv6-Prefix	123	ipv6prefix
ATTRIBUTE	Framed-IPv6-Address	168	ipv6addr
ATTRIBUTE	DNS-Server-IPv6-Address	169	ipv6addr
ATTRIBUTE	Framed-IPv6-Prefix	97	ipv6prefix
ATTRIBUTE	Route-IPv6-Information	170	ipv6prefix
`

func radiusConfigPath(o store.OCServState) string {
	if p := strings.TrimSpace(o.Radius.ConfigPath); p != "" {
		return p
	}
	return RadiusClientConfPath
}

// WriteRadcliConfig writes /etc/radcli/* for ocserv radius auth.
func WriteRadcliConfig(o store.OCServState) error {
	if !store.OCServUsesRadius(o) {
		return nil
	}
	r := o.Radius
	host := strings.TrimSpace(r.Server)
	if host == "" {
		return fmt.Errorf("radius server required")
	}
	secret := strings.TrimSpace(r.Secret)
	if secret == "" {
		return fmt.Errorf("radius secret required")
	}
	authPort := r.AuthPort
	if authPort <= 0 {
		authPort = 1812
	}
	acctPort := r.AcctPort
	if acctPort <= 0 {
		acctPort = 1813
	}
	if err := os.MkdirAll(RadcliDir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(RadcliDictionaryPath, []byte(radcliDictionary), 0644); err != nil {
		return err
	}
	authAddr := formatRadiusHostPort(host, authPort)
	acctAddr := formatRadiusHostPort(host, acctPort)
	servers := fmt.Sprintf("%s\t%s\t3\n", authAddr, secret)
	if err := os.WriteFile(RadcliServersPath, []byte(servers), 0600); err != nil {
		return err
	}
	conf := fmt.Sprintf(`# Generated by qosnatd — do not edit manually; use Web UI
authserver %s
acctserver %s
servers %s
dictionary %s
bindaddr *
radius_timeout 10
radius_retries 3
`, authAddr, acctAddr, RadcliServersPath, RadcliDictionaryPath)
	if err := os.WriteFile(RadiusClientConfPath, []byte(conf), 0644); err != nil {
		return err
	}
	return nil
}

func formatRadiusHostPort(host string, port int) string {
	host = strings.TrimSpace(host)
	if strings.HasPrefix(host, "[") {
		return fmt.Sprintf("%s:%d", host, port)
	}
	if strings.Contains(host, ":") && !strings.Contains(host, ".") {
		return fmt.Sprintf("[%s]:%d", host, port)
	}
	return fmt.Sprintf("%s:%d", host, port)
}

func radiusAuthDirective(o store.OCServState) string {
	cfg := radiusConfigPath(o)
	opts := []string{"config=" + cfg}
	if o.Radius.GroupConfig {
		opts = append(opts, "groupconfig=true")
	}
	if nas := strings.TrimSpace(o.Radius.NASIdentifier); nas != "" {
		opts = append(opts, "nas-identifier="+nas)
	}
	return fmt.Sprintf(`auth = "radius[%s]"`, strings.Join(opts, ","))
}

func radiusAcctLines(o store.OCServState) []string {
	if !o.Radius.AcctEnabled {
		return nil
	}
	cfg := radiusConfigPath(o)
	interval := o.Radius.StatsReportTime
	if interval <= 0 {
		interval = 360
	}
	return []string{
		fmt.Sprintf(`acct = "radius[config=%s]"`, cfg),
		fmt.Sprintf("stats-report-time = %d", interval),
	}
}

// RadiusLinked reports whether ocserv was built with radcli/radiusclient.
func RadiusLinked() bool {
	bin := BinaryPath
	if p, err := exec.LookPath("ocserv"); err == nil {
		bin = p
	} else if _, err := os.Stat(BinaryPath); err != nil {
		return false
	}
	out, err := exec.Command("ldd", bin).CombinedOutput()
	if err != nil {
		return false
	}
	s := string(out)
	return strings.Contains(s, "radcli") || strings.Contains(s, "radiusclient")
}
